@startuml
autoactivate on
boundary api 
participant account #cyan
participant credentials #cyan
database Repository as db
boundary notification

== get user ==
api -> account: get user
alt user in database
  account -> db: get user data
  return user data
  account -> account: set result to user data
  return
else user not in database
  account -> account: set result to error
  return result
end
return result

== add user ==
api -> account: add user
  alt user not in database
    account -> account: create new user
    return
    account -> credentials: create credentials
    return
    account -> db: insert user data
    return
    account -> notification: send activation email
    return
  else user in database
    account -> account: set result to error
    return result
  end
return result

== update user ==
api -> account: update user
account -> credentials: update credentials
return
account -> db: update user
return
return result

== delete user ==
api -> account: delete user
account -> credentials: delete credentials for user
return
account -> db: delete user
return
return result

== activate user ==
api -> account: activate user
account -> account: update user
return
account -> notification: send welcome email
return
return result
@enduml