@startuml
autoactivate on
actor user 
box Try Your Ideas
  participant TyiUI #cyan
  participant TyiAPI #cyan
  participant credentials #cyan
end box

user -> TyiUI: SignIn Request 

TyiUI -> TyiAPI: signIn

TyiAPI -> credentials: signIn
return session token
TyiAPI -> TyiAPI: Set session accessToken
return
return 
return Redirect to main area
@enduml