<template>
  <div class="bg-transparent/30 text-transparent/30 shadow-transparent/30 border-transparent/30 divide-transparent/30 ring-transparent/30 outline-transparent/30 from-transparent/30 via-transparent/30 to-transparent/30 fill-transparent/30 accent-transparent/30  ">-transparent </div>
  <div class="bg-white/30 text-white/30 shadow-white/30 border-white/30 divide-white/30 ring-white/30 outline-white/30 from-white/30 via-white/30 to-white/30 fill-white/30 accent-white/30  ">-white </div>
  <div class="bg-black/30 text-black/30 shadow-black/30 border-black/30 divide-black/30 ring-black/30 outline-black/30 from-black/30 via-black/30 to-black/30 fill-black/30 accent-black/30  ">-black </div>
  <div class="bg-inherit/30 text-inherit/30 shadow-inherit/30 border-inherit/30 divide-inherit/30 ring-inherit/30 outline-inherit/30 from-inherit/30 via-inherit/30 to-inherit/30 fill-inherit/30 accent-inherit/30  ">-inherit </div>
  <div class="bg-current/30 text-current/30 shadow-current/30 border-current/30 divide-current/30 ring-current/30 outline-current/30 from-current/30 via-current/30 to-current/30 fill-current/30 accent-current/30  ">-current </div>
  <div class="hover:bg-transparent/30 hover:text-transparent/30 hover:shadow-transparent/30 hover:border-transparent/30 hover:divide-transparent/30 hover:ring-transparent/30 hover:outline-transparent/30 hover:from-transparent/30 hover:via-transparent/30 hover:to-transparent/30 hover:fill-transparent/30 hover:accent-transparent/30  ">hover:-transparent </div>
  <div class="hover:bg-white/30 hover:text-white/30 hover:shadow-white/30 hover:border-white/30 hover:divide-white/30 hover:ring-white/30 hover:outline-white/30 hover:from-white/30 hover:via-white/30 hover:to-white/30 hover:fill-white/30 hover:accent-white/30  ">hover:-white </div>
  <div class="hover:bg-black/30 hover:text-black/30 hover:shadow-black/30 hover:border-black/30 hover:divide-black/30 hover:ring-black/30 hover:outline-black/30 hover:from-black/30 hover:via-black/30 hover:to-black/30 hover:fill-black/30 hover:accent-black/30  ">hover:-black </div>
  <div class="hover:bg-inherit/30 hover:text-inherit/30 hover:shadow-inherit/30 hover:border-inherit/30 hover:divide-inherit/30 hover:ring-inherit/30 hover:outline-inherit/30 hover:from-inherit/30 hover:via-inherit/30 hover:to-inherit/30 hover:fill-inherit/30 hover:accent-inherit/30  ">hover:-inherit </div>
  <div class="hover:bg-current/30 hover:text-current/30 hover:shadow-current/30 hover:border-current/30 hover:divide-current/30 hover:ring-current/30 hover:outline-current/30 hover:from-current/30 hover:via-current/30 hover:to-current/30 hover:fill-current/30 hover:accent-current/30  ">hover:-current </div>
  <div class="active:bg-transparent/30 active:text-transparent/30 active:shadow-transparent/30 active:border-transparent/30 active:divide-transparent/30 active:ring-transparent/30 active:outline-transparent/30 active:from-transparent/30 active:via-transparent/30 active:to-transparent/30 active:fill-transparent/30 active:accent-transparent/30  ">active:-transparent </div>
  <div class="active:bg-white/30 active:text-white/30 active:shadow-white/30 active:border-white/30 active:divide-white/30 active:ring-white/30 active:outline-white/30 active:from-white/30 active:via-white/30 active:to-white/30 active:fill-white/30 active:accent-white/30  ">active:-white </div>
  <div class="active:bg-black/30 active:text-black/30 active:shadow-black/30 active:border-black/30 active:divide-black/30 active:ring-black/30 active:outline-black/30 active:from-black/30 active:via-black/30 active:to-black/30 active:fill-black/30 active:accent-black/30  ">active:-black </div>
  <div class="active:bg-inherit/30 active:text-inherit/30 active:shadow-inherit/30 active:border-inherit/30 active:divide-inherit/30 active:ring-inherit/30 active:outline-inherit/30 active:from-inherit/30 active:via-inherit/30 active:to-inherit/30 active:fill-inherit/30 active:accent-inherit/30  ">active:-inherit </div>
  <div class="active:bg-current/30 active:text-current/30 active:shadow-current/30 active:border-current/30 active:divide-current/30 active:ring-current/30 active:outline-current/30 active:from-current/30 active:via-current/30 active:to-current/30 active:fill-current/30 active:accent-current/30  ">active:-current </div>
  <div class="focus:bg-transparent/30 focus:text-transparent/30 focus:shadow-transparent/30 focus:border-transparent/30 focus:divide-transparent/30 focus:ring-transparent/30 focus:outline-transparent/30 focus:from-transparent/30 focus:via-transparent/30 focus:to-transparent/30 focus:fill-transparent/30 focus:accent-transparent/30  ">focus:-transparent </div>
  <div class="focus:bg-white/30 focus:text-white/30 focus:shadow-white/30 focus:border-white/30 focus:divide-white/30 focus:ring-white/30 focus:outline-white/30 focus:from-white/30 focus:via-white/30 focus:to-white/30 focus:fill-white/30 focus:accent-white/30  ">focus:-white </div>
  <div class="focus:bg-black/30 focus:text-black/30 focus:shadow-black/30 focus:border-black/30 focus:divide-black/30 focus:ring-black/30 focus:outline-black/30 focus:from-black/30 focus:via-black/30 focus:to-black/30 focus:fill-black/30 focus:accent-black/30  ">focus:-black </div>
  <div class="focus:bg-inherit/30 focus:text-inherit/30 focus:shadow-inherit/30 focus:border-inherit/30 focus:divide-inherit/30 focus:ring-inherit/30 focus:outline-inherit/30 focus:from-inherit/30 focus:via-inherit/30 focus:to-inherit/30 focus:fill-inherit/30 focus:accent-inherit/30  ">focus:-inherit </div>
  <div class="focus:bg-current/30 focus:text-current/30 focus:shadow-current/30 focus:border-current/30 focus:divide-current/30 focus:ring-current/30 focus:outline-current/30 focus:from-current/30 focus:via-current/30 focus:to-current/30 focus:fill-current/30 focus:accent-current/30  ">focus:-current </div>
  
  </template>