<template>
  <div class="transition-none ">-none </div>
  <div class="transition-all ">-all </div>
  <div class="transition-colors ">-colors </div>
  <div class="transition-opacity ">-opacity </div>
  <div class="transition-shadow ">-shadow </div>
  <div class="transition-transform ">-transform </div>
  <div class="hover:transition-none ">hover:-none </div>
  <div class="hover:transition-all ">hover:-all </div>
  <div class="hover:transition-colors ">hover:-colors </div>
  <div class="hover:transition-opacity ">hover:-opacity </div>
  <div class="hover:transition-shadow ">hover:-shadow </div>
  <div class="hover:transition-transform ">hover:-transform </div>
  <div class="active:transition-none ">active:-none </div>
  <div class="active:transition-all ">active:-all </div>
  <div class="active:transition-colors ">active:-colors </div>
  <div class="active:transition-opacity ">active:-opacity </div>
  <div class="active:transition-shadow ">active:-shadow </div>
  <div class="active:transition-transform ">active:-transform </div>
  <div class="focus:transition-none ">focus:-none </div>
  <div class="focus:transition-all ">focus:-all </div>
  <div class="focus:transition-colors ">focus:-colors </div>
  <div class="focus:transition-opacity ">focus:-opacity </div>
  <div class="focus:transition-shadow ">focus:-shadow </div>
  <div class="focus:transition-transform ">focus:-transform </div>
  <div class="sm:transition-none ">sm:-none </div>
  <div class="sm:transition-all ">sm:-all </div>
  <div class="sm:transition-colors ">sm:-colors </div>
  <div class="sm:transition-opacity ">sm:-opacity </div>
  <div class="sm:transition-shadow ">sm:-shadow </div>
  <div class="sm:transition-transform ">sm:-transform </div>
  <div class="sm:hover:transition-none ">sm:hover:-none </div>
  <div class="sm:hover:transition-all ">sm:hover:-all </div>
  <div class="sm:hover:transition-colors ">sm:hover:-colors </div>
  <div class="sm:hover:transition-opacity ">sm:hover:-opacity </div>
  <div class="sm:hover:transition-shadow ">sm:hover:-shadow </div>
  <div class="sm:hover:transition-transform ">sm:hover:-transform </div>
  <div class="sm:active:transition-none ">sm:active:-none </div>
  <div class="sm:active:transition-all ">sm:active:-all </div>
  <div class="sm:active:transition-colors ">sm:active:-colors </div>
  <div class="sm:active:transition-opacity ">sm:active:-opacity </div>
  <div class="sm:active:transition-shadow ">sm:active:-shadow </div>
  <div class="sm:active:transition-transform ">sm:active:-transform </div>
  <div class="sm:focus:transition-none ">sm:focus:-none </div>
  <div class="sm:focus:transition-all ">sm:focus:-all </div>
  <div class="sm:focus:transition-colors ">sm:focus:-colors </div>
  <div class="sm:focus:transition-opacity ">sm:focus:-opacity </div>
  <div class="sm:focus:transition-shadow ">sm:focus:-shadow </div>
  <div class="sm:focus:transition-transform ">sm:focus:-transform </div>
  <div class="md:transition-none ">md:-none </div>
  <div class="md:transition-all ">md:-all </div>
  <div class="md:transition-colors ">md:-colors </div>
  <div class="md:transition-opacity ">md:-opacity </div>
  <div class="md:transition-shadow ">md:-shadow </div>
  <div class="md:transition-transform ">md:-transform </div>
  <div class="md:hover:transition-none ">md:hover:-none </div>
  <div class="md:hover:transition-all ">md:hover:-all </div>
  <div class="md:hover:transition-colors ">md:hover:-colors </div>
  <div class="md:hover:transition-opacity ">md:hover:-opacity </div>
  <div class="md:hover:transition-shadow ">md:hover:-shadow </div>
  <div class="md:hover:transition-transform ">md:hover:-transform </div>
  <div class="md:active:transition-none ">md:active:-none </div>
  <div class="md:active:transition-all ">md:active:-all </div>
  <div class="md:active:transition-colors ">md:active:-colors </div>
  <div class="md:active:transition-opacity ">md:active:-opacity </div>
  <div class="md:active:transition-shadow ">md:active:-shadow </div>
  <div class="md:active:transition-transform ">md:active:-transform </div>
  <div class="md:focus:transition-none ">md:focus:-none </div>
  <div class="md:focus:transition-all ">md:focus:-all </div>
  <div class="md:focus:transition-colors ">md:focus:-colors </div>
  <div class="md:focus:transition-opacity ">md:focus:-opacity </div>
  <div class="md:focus:transition-shadow ">md:focus:-shadow </div>
  <div class="md:focus:transition-transform ">md:focus:-transform </div>
  <div class="lg:transition-none ">lg:-none </div>
  <div class="lg:transition-all ">lg:-all </div>
  <div class="lg:transition-colors ">lg:-colors </div>
  <div class="lg:transition-opacity ">lg:-opacity </div>
  <div class="lg:transition-shadow ">lg:-shadow </div>
  <div class="lg:transition-transform ">lg:-transform </div>
  <div class="lg:hover:transition-none ">lg:hover:-none </div>
  <div class="lg:hover:transition-all ">lg:hover:-all </div>
  <div class="lg:hover:transition-colors ">lg:hover:-colors </div>
  <div class="lg:hover:transition-opacity ">lg:hover:-opacity </div>
  <div class="lg:hover:transition-shadow ">lg:hover:-shadow </div>
  <div class="lg:hover:transition-transform ">lg:hover:-transform </div>
  <div class="lg:active:transition-none ">lg:active:-none </div>
  <div class="lg:active:transition-all ">lg:active:-all </div>
  <div class="lg:active:transition-colors ">lg:active:-colors </div>
  <div class="lg:active:transition-opacity ">lg:active:-opacity </div>
  <div class="lg:active:transition-shadow ">lg:active:-shadow </div>
  <div class="lg:active:transition-transform ">lg:active:-transform </div>
  <div class="lg:focus:transition-none ">lg:focus:-none </div>
  <div class="lg:focus:transition-all ">lg:focus:-all </div>
  <div class="lg:focus:transition-colors ">lg:focus:-colors </div>
  <div class="lg:focus:transition-opacity ">lg:focus:-opacity </div>
  <div class="lg:focus:transition-shadow ">lg:focus:-shadow </div>
  <div class="lg:focus:transition-transform ">lg:focus:-transform </div>
  <div class="xl:transition-none ">xl:-none </div>
  <div class="xl:transition-all ">xl:-all </div>
  <div class="xl:transition-colors ">xl:-colors </div>
  <div class="xl:transition-opacity ">xl:-opacity </div>
  <div class="xl:transition-shadow ">xl:-shadow </div>
  <div class="xl:transition-transform ">xl:-transform </div>
  <div class="xl:hover:transition-none ">xl:hover:-none </div>
  <div class="xl:hover:transition-all ">xl:hover:-all </div>
  <div class="xl:hover:transition-colors ">xl:hover:-colors </div>
  <div class="xl:hover:transition-opacity ">xl:hover:-opacity </div>
  <div class="xl:hover:transition-shadow ">xl:hover:-shadow </div>
  <div class="xl:hover:transition-transform ">xl:hover:-transform </div>
  <div class="xl:active:transition-none ">xl:active:-none </div>
  <div class="xl:active:transition-all ">xl:active:-all </div>
  <div class="xl:active:transition-colors ">xl:active:-colors </div>
  <div class="xl:active:transition-opacity ">xl:active:-opacity </div>
  <div class="xl:active:transition-shadow ">xl:active:-shadow </div>
  <div class="xl:active:transition-transform ">xl:active:-transform </div>
  <div class="xl:focus:transition-none ">xl:focus:-none </div>
  <div class="xl:focus:transition-all ">xl:focus:-all </div>
  <div class="xl:focus:transition-colors ">xl:focus:-colors </div>
  <div class="xl:focus:transition-opacity ">xl:focus:-opacity </div>
  <div class="xl:focus:transition-shadow ">xl:focus:-shadow </div>
  <div class="xl:focus:transition-transform ">xl:focus:-transform </div>
  <div class="dark:transition-none ">dark:-none </div>
  <div class="dark:transition-all ">dark:-all </div>
  <div class="dark:transition-colors ">dark:-colors </div>
  <div class="dark:transition-opacity ">dark:-opacity </div>
  <div class="dark:transition-shadow ">dark:-shadow </div>
  <div class="dark:transition-transform ">dark:-transform </div>
  <div class="dark:hover:transition-none ">dark:hover:-none </div>
  <div class="dark:hover:transition-all ">dark:hover:-all </div>
  <div class="dark:hover:transition-colors ">dark:hover:-colors </div>
  <div class="dark:hover:transition-opacity ">dark:hover:-opacity </div>
  <div class="dark:hover:transition-shadow ">dark:hover:-shadow </div>
  <div class="dark:hover:transition-transform ">dark:hover:-transform </div>
  <div class="dark:active:transition-none ">dark:active:-none </div>
  <div class="dark:active:transition-all ">dark:active:-all </div>
  <div class="dark:active:transition-colors ">dark:active:-colors </div>
  <div class="dark:active:transition-opacity ">dark:active:-opacity </div>
  <div class="dark:active:transition-shadow ">dark:active:-shadow </div>
  <div class="dark:active:transition-transform ">dark:active:-transform </div>
  <div class="dark:focus:transition-none ">dark:focus:-none </div>
  <div class="dark:focus:transition-all ">dark:focus:-all </div>
  <div class="dark:focus:transition-colors ">dark:focus:-colors </div>
  <div class="dark:focus:transition-opacity ">dark:focus:-opacity </div>
  <div class="dark:focus:transition-shadow ">dark:focus:-shadow </div>
  <div class="dark:focus:transition-transform ">dark:focus:-transform </div>
  <div class="dark:sm:transition-none ">dark:sm:-none </div>
  <div class="dark:sm:transition-all ">dark:sm:-all </div>
  <div class="dark:sm:transition-colors ">dark:sm:-colors </div>
  <div class="dark:sm:transition-opacity ">dark:sm:-opacity </div>
  <div class="dark:sm:transition-shadow ">dark:sm:-shadow </div>
  <div class="dark:sm:transition-transform ">dark:sm:-transform </div>
  <div class="dark:sm:hover:transition-none ">dark:sm:hover:-none </div>
  <div class="dark:sm:hover:transition-all ">dark:sm:hover:-all </div>
  <div class="dark:sm:hover:transition-colors ">dark:sm:hover:-colors </div>
  <div class="dark:sm:hover:transition-opacity ">dark:sm:hover:-opacity </div>
  <div class="dark:sm:hover:transition-shadow ">dark:sm:hover:-shadow </div>
  <div class="dark:sm:hover:transition-transform ">dark:sm:hover:-transform </div>
  <div class="dark:sm:active:transition-none ">dark:sm:active:-none </div>
  <div class="dark:sm:active:transition-all ">dark:sm:active:-all </div>
  <div class="dark:sm:active:transition-colors ">dark:sm:active:-colors </div>
  <div class="dark:sm:active:transition-opacity ">dark:sm:active:-opacity </div>
  <div class="dark:sm:active:transition-shadow ">dark:sm:active:-shadow </div>
  <div class="dark:sm:active:transition-transform ">dark:sm:active:-transform </div>
  <div class="dark:sm:focus:transition-none ">dark:sm:focus:-none </div>
  <div class="dark:sm:focus:transition-all ">dark:sm:focus:-all </div>
  <div class="dark:sm:focus:transition-colors ">dark:sm:focus:-colors </div>
  <div class="dark:sm:focus:transition-opacity ">dark:sm:focus:-opacity </div>
  <div class="dark:sm:focus:transition-shadow ">dark:sm:focus:-shadow </div>
  <div class="dark:sm:focus:transition-transform ">dark:sm:focus:-transform </div>
  <div class="dark:md:transition-none ">dark:md:-none </div>
  <div class="dark:md:transition-all ">dark:md:-all </div>
  <div class="dark:md:transition-colors ">dark:md:-colors </div>
  <div class="dark:md:transition-opacity ">dark:md:-opacity </div>
  <div class="dark:md:transition-shadow ">dark:md:-shadow </div>
  <div class="dark:md:transition-transform ">dark:md:-transform </div>
  <div class="dark:md:hover:transition-none ">dark:md:hover:-none </div>
  <div class="dark:md:hover:transition-all ">dark:md:hover:-all </div>
  <div class="dark:md:hover:transition-colors ">dark:md:hover:-colors </div>
  <div class="dark:md:hover:transition-opacity ">dark:md:hover:-opacity </div>
  <div class="dark:md:hover:transition-shadow ">dark:md:hover:-shadow </div>
  <div class="dark:md:hover:transition-transform ">dark:md:hover:-transform </div>
  <div class="dark:md:active:transition-none ">dark:md:active:-none </div>
  <div class="dark:md:active:transition-all ">dark:md:active:-all </div>
  <div class="dark:md:active:transition-colors ">dark:md:active:-colors </div>
  <div class="dark:md:active:transition-opacity ">dark:md:active:-opacity </div>
  <div class="dark:md:active:transition-shadow ">dark:md:active:-shadow </div>
  <div class="dark:md:active:transition-transform ">dark:md:active:-transform </div>
  <div class="dark:md:focus:transition-none ">dark:md:focus:-none </div>
  <div class="dark:md:focus:transition-all ">dark:md:focus:-all </div>
  <div class="dark:md:focus:transition-colors ">dark:md:focus:-colors </div>
  <div class="dark:md:focus:transition-opacity ">dark:md:focus:-opacity </div>
  <div class="dark:md:focus:transition-shadow ">dark:md:focus:-shadow </div>
  <div class="dark:md:focus:transition-transform ">dark:md:focus:-transform </div>
  <div class="dark:lg:transition-none ">dark:lg:-none </div>
  <div class="dark:lg:transition-all ">dark:lg:-all </div>
  <div class="dark:lg:transition-colors ">dark:lg:-colors </div>
  <div class="dark:lg:transition-opacity ">dark:lg:-opacity </div>
  <div class="dark:lg:transition-shadow ">dark:lg:-shadow </div>
  <div class="dark:lg:transition-transform ">dark:lg:-transform </div>
  <div class="dark:lg:hover:transition-none ">dark:lg:hover:-none </div>
  <div class="dark:lg:hover:transition-all ">dark:lg:hover:-all </div>
  <div class="dark:lg:hover:transition-colors ">dark:lg:hover:-colors </div>
  <div class="dark:lg:hover:transition-opacity ">dark:lg:hover:-opacity </div>
  <div class="dark:lg:hover:transition-shadow ">dark:lg:hover:-shadow </div>
  <div class="dark:lg:hover:transition-transform ">dark:lg:hover:-transform </div>
  <div class="dark:lg:active:transition-none ">dark:lg:active:-none </div>
  <div class="dark:lg:active:transition-all ">dark:lg:active:-all </div>
  <div class="dark:lg:active:transition-colors ">dark:lg:active:-colors </div>
  <div class="dark:lg:active:transition-opacity ">dark:lg:active:-opacity </div>
  <div class="dark:lg:active:transition-shadow ">dark:lg:active:-shadow </div>
  <div class="dark:lg:active:transition-transform ">dark:lg:active:-transform </div>
  <div class="dark:lg:focus:transition-none ">dark:lg:focus:-none </div>
  <div class="dark:lg:focus:transition-all ">dark:lg:focus:-all </div>
  <div class="dark:lg:focus:transition-colors ">dark:lg:focus:-colors </div>
  <div class="dark:lg:focus:transition-opacity ">dark:lg:focus:-opacity </div>
  <div class="dark:lg:focus:transition-shadow ">dark:lg:focus:-shadow </div>
  <div class="dark:lg:focus:transition-transform ">dark:lg:focus:-transform </div>
  <div class="dark:xl:transition-none ">dark:xl:-none </div>
  <div class="dark:xl:transition-all ">dark:xl:-all </div>
  <div class="dark:xl:transition-colors ">dark:xl:-colors </div>
  <div class="dark:xl:transition-opacity ">dark:xl:-opacity </div>
  <div class="dark:xl:transition-shadow ">dark:xl:-shadow </div>
  <div class="dark:xl:transition-transform ">dark:xl:-transform </div>
  <div class="dark:xl:hover:transition-none ">dark:xl:hover:-none </div>
  <div class="dark:xl:hover:transition-all ">dark:xl:hover:-all </div>
  <div class="dark:xl:hover:transition-colors ">dark:xl:hover:-colors </div>
  <div class="dark:xl:hover:transition-opacity ">dark:xl:hover:-opacity </div>
  <div class="dark:xl:hover:transition-shadow ">dark:xl:hover:-shadow </div>
  <div class="dark:xl:hover:transition-transform ">dark:xl:hover:-transform </div>
  <div class="dark:xl:active:transition-none ">dark:xl:active:-none </div>
  <div class="dark:xl:active:transition-all ">dark:xl:active:-all </div>
  <div class="dark:xl:active:transition-colors ">dark:xl:active:-colors </div>
  <div class="dark:xl:active:transition-opacity ">dark:xl:active:-opacity </div>
  <div class="dark:xl:active:transition-shadow ">dark:xl:active:-shadow </div>
  <div class="dark:xl:active:transition-transform ">dark:xl:active:-transform </div>
  <div class="dark:xl:focus:transition-none ">dark:xl:focus:-none </div>
  <div class="dark:xl:focus:transition-all ">dark:xl:focus:-all </div>
  <div class="dark:xl:focus:transition-colors ">dark:xl:focus:-colors </div>
  <div class="dark:xl:focus:transition-opacity ">dark:xl:focus:-opacity </div>
  <div class="dark:xl:focus:transition-shadow ">dark:xl:focus:-shadow </div>
  <div class="dark:xl:focus:transition-transform ">dark:xl:focus:-transform </div>
  <div class="delay-0 duration-0 ">-0 </div>
  <div class="delay-75 duration-75 ">-75 </div>
  <div class="delay-100 duration-100 ">-100 </div>
  <div class="delay-150 duration-150 ">-150 </div>
  <div class="delay-200 duration-200 ">-200 </div>
  <div class="delay-300 duration-300 ">-300 </div>
  <div class="delay-500 duration-500 ">-500 </div>
  <div class="delay-700 duration-700 ">-700 </div>
  <div class="delay-1000 duration-1000 ">-1000 </div>
  <div class="hover:delay-0 hover:duration-0 ">hover:-0 </div>
  <div class="hover:delay-75 hover:duration-75 ">hover:-75 </div>
  <div class="hover:delay-100 hover:duration-100 ">hover:-100 </div>
  <div class="hover:delay-150 hover:duration-150 ">hover:-150 </div>
  <div class="hover:delay-200 hover:duration-200 ">hover:-200 </div>
  <div class="hover:delay-300 hover:duration-300 ">hover:-300 </div>
  <div class="hover:delay-500 hover:duration-500 ">hover:-500 </div>
  <div class="hover:delay-700 hover:duration-700 ">hover:-700 </div>
  <div class="hover:delay-1000 hover:duration-1000 ">hover:-1000 </div>
  <div class="active:delay-0 active:duration-0 ">active:-0 </div>
  <div class="active:delay-75 active:duration-75 ">active:-75 </div>
  <div class="active:delay-100 active:duration-100 ">active:-100 </div>
  <div class="active:delay-150 active:duration-150 ">active:-150 </div>
  <div class="active:delay-200 active:duration-200 ">active:-200 </div>
  <div class="active:delay-300 active:duration-300 ">active:-300 </div>
  <div class="active:delay-500 active:duration-500 ">active:-500 </div>
  <div class="active:delay-700 active:duration-700 ">active:-700 </div>
  <div class="active:delay-1000 active:duration-1000 ">active:-1000 </div>
  <div class="focus:delay-0 focus:duration-0 ">focus:-0 </div>
  <div class="focus:delay-75 focus:duration-75 ">focus:-75 </div>
  <div class="focus:delay-100 focus:duration-100 ">focus:-100 </div>
  <div class="focus:delay-150 focus:duration-150 ">focus:-150 </div>
  <div class="focus:delay-200 focus:duration-200 ">focus:-200 </div>
  <div class="focus:delay-300 focus:duration-300 ">focus:-300 </div>
  <div class="focus:delay-500 focus:duration-500 ">focus:-500 </div>
  <div class="focus:delay-700 focus:duration-700 ">focus:-700 </div>
  <div class="focus:delay-1000 focus:duration-1000 ">focus:-1000 </div>
  <div class="sm:delay-0 sm:duration-0 ">sm:-0 </div>
  <div class="sm:delay-75 sm:duration-75 ">sm:-75 </div>
  <div class="sm:delay-100 sm:duration-100 ">sm:-100 </div>
  <div class="sm:delay-150 sm:duration-150 ">sm:-150 </div>
  <div class="sm:delay-200 sm:duration-200 ">sm:-200 </div>
  <div class="sm:delay-300 sm:duration-300 ">sm:-300 </div>
  <div class="sm:delay-500 sm:duration-500 ">sm:-500 </div>
  <div class="sm:delay-700 sm:duration-700 ">sm:-700 </div>
  <div class="sm:delay-1000 sm:duration-1000 ">sm:-1000 </div>
  <div class="sm:hover:delay-0 sm:hover:duration-0 ">sm:hover:-0 </div>
  <div class="sm:hover:delay-75 sm:hover:duration-75 ">sm:hover:-75 </div>
  <div class="sm:hover:delay-100 sm:hover:duration-100 ">sm:hover:-100 </div>
  <div class="sm:hover:delay-150 sm:hover:duration-150 ">sm:hover:-150 </div>
  <div class="sm:hover:delay-200 sm:hover:duration-200 ">sm:hover:-200 </div>
  <div class="sm:hover:delay-300 sm:hover:duration-300 ">sm:hover:-300 </div>
  <div class="sm:hover:delay-500 sm:hover:duration-500 ">sm:hover:-500 </div>
  <div class="sm:hover:delay-700 sm:hover:duration-700 ">sm:hover:-700 </div>
  <div class="sm:hover:delay-1000 sm:hover:duration-1000 ">sm:hover:-1000 </div>
  <div class="sm:active:delay-0 sm:active:duration-0 ">sm:active:-0 </div>
  <div class="sm:active:delay-75 sm:active:duration-75 ">sm:active:-75 </div>
  <div class="sm:active:delay-100 sm:active:duration-100 ">sm:active:-100 </div>
  <div class="sm:active:delay-150 sm:active:duration-150 ">sm:active:-150 </div>
  <div class="sm:active:delay-200 sm:active:duration-200 ">sm:active:-200 </div>
  <div class="sm:active:delay-300 sm:active:duration-300 ">sm:active:-300 </div>
  <div class="sm:active:delay-500 sm:active:duration-500 ">sm:active:-500 </div>
  <div class="sm:active:delay-700 sm:active:duration-700 ">sm:active:-700 </div>
  <div class="sm:active:delay-1000 sm:active:duration-1000 ">sm:active:-1000 </div>
  <div class="sm:focus:delay-0 sm:focus:duration-0 ">sm:focus:-0 </div>
  <div class="sm:focus:delay-75 sm:focus:duration-75 ">sm:focus:-75 </div>
  <div class="sm:focus:delay-100 sm:focus:duration-100 ">sm:focus:-100 </div>
  <div class="sm:focus:delay-150 sm:focus:duration-150 ">sm:focus:-150 </div>
  <div class="sm:focus:delay-200 sm:focus:duration-200 ">sm:focus:-200 </div>
  <div class="sm:focus:delay-300 sm:focus:duration-300 ">sm:focus:-300 </div>
  <div class="sm:focus:delay-500 sm:focus:duration-500 ">sm:focus:-500 </div>
  <div class="sm:focus:delay-700 sm:focus:duration-700 ">sm:focus:-700 </div>
  <div class="sm:focus:delay-1000 sm:focus:duration-1000 ">sm:focus:-1000 </div>
  <div class="md:delay-0 md:duration-0 ">md:-0 </div>
  <div class="md:delay-75 md:duration-75 ">md:-75 </div>
  <div class="md:delay-100 md:duration-100 ">md:-100 </div>
  <div class="md:delay-150 md:duration-150 ">md:-150 </div>
  <div class="md:delay-200 md:duration-200 ">md:-200 </div>
  <div class="md:delay-300 md:duration-300 ">md:-300 </div>
  <div class="md:delay-500 md:duration-500 ">md:-500 </div>
  <div class="md:delay-700 md:duration-700 ">md:-700 </div>
  <div class="md:delay-1000 md:duration-1000 ">md:-1000 </div>
  <div class="md:hover:delay-0 md:hover:duration-0 ">md:hover:-0 </div>
  <div class="md:hover:delay-75 md:hover:duration-75 ">md:hover:-75 </div>
  <div class="md:hover:delay-100 md:hover:duration-100 ">md:hover:-100 </div>
  <div class="md:hover:delay-150 md:hover:duration-150 ">md:hover:-150 </div>
  <div class="md:hover:delay-200 md:hover:duration-200 ">md:hover:-200 </div>
  <div class="md:hover:delay-300 md:hover:duration-300 ">md:hover:-300 </div>
  <div class="md:hover:delay-500 md:hover:duration-500 ">md:hover:-500 </div>
  <div class="md:hover:delay-700 md:hover:duration-700 ">md:hover:-700 </div>
  <div class="md:hover:delay-1000 md:hover:duration-1000 ">md:hover:-1000 </div>
  <div class="md:active:delay-0 md:active:duration-0 ">md:active:-0 </div>
  <div class="md:active:delay-75 md:active:duration-75 ">md:active:-75 </div>
  <div class="md:active:delay-100 md:active:duration-100 ">md:active:-100 </div>
  <div class="md:active:delay-150 md:active:duration-150 ">md:active:-150 </div>
  <div class="md:active:delay-200 md:active:duration-200 ">md:active:-200 </div>
  <div class="md:active:delay-300 md:active:duration-300 ">md:active:-300 </div>
  <div class="md:active:delay-500 md:active:duration-500 ">md:active:-500 </div>
  <div class="md:active:delay-700 md:active:duration-700 ">md:active:-700 </div>
  <div class="md:active:delay-1000 md:active:duration-1000 ">md:active:-1000 </div>
  <div class="md:focus:delay-0 md:focus:duration-0 ">md:focus:-0 </div>
  <div class="md:focus:delay-75 md:focus:duration-75 ">md:focus:-75 </div>
  <div class="md:focus:delay-100 md:focus:duration-100 ">md:focus:-100 </div>
  <div class="md:focus:delay-150 md:focus:duration-150 ">md:focus:-150 </div>
  <div class="md:focus:delay-200 md:focus:duration-200 ">md:focus:-200 </div>
  <div class="md:focus:delay-300 md:focus:duration-300 ">md:focus:-300 </div>
  <div class="md:focus:delay-500 md:focus:duration-500 ">md:focus:-500 </div>
  <div class="md:focus:delay-700 md:focus:duration-700 ">md:focus:-700 </div>
  <div class="md:focus:delay-1000 md:focus:duration-1000 ">md:focus:-1000 </div>
  <div class="lg:delay-0 lg:duration-0 ">lg:-0 </div>
  <div class="lg:delay-75 lg:duration-75 ">lg:-75 </div>
  <div class="lg:delay-100 lg:duration-100 ">lg:-100 </div>
  <div class="lg:delay-150 lg:duration-150 ">lg:-150 </div>
  <div class="lg:delay-200 lg:duration-200 ">lg:-200 </div>
  <div class="lg:delay-300 lg:duration-300 ">lg:-300 </div>
  <div class="lg:delay-500 lg:duration-500 ">lg:-500 </div>
  <div class="lg:delay-700 lg:duration-700 ">lg:-700 </div>
  <div class="lg:delay-1000 lg:duration-1000 ">lg:-1000 </div>
  <div class="lg:hover:delay-0 lg:hover:duration-0 ">lg:hover:-0 </div>
  <div class="lg:hover:delay-75 lg:hover:duration-75 ">lg:hover:-75 </div>
  <div class="lg:hover:delay-100 lg:hover:duration-100 ">lg:hover:-100 </div>
  <div class="lg:hover:delay-150 lg:hover:duration-150 ">lg:hover:-150 </div>
  <div class="lg:hover:delay-200 lg:hover:duration-200 ">lg:hover:-200 </div>
  <div class="lg:hover:delay-300 lg:hover:duration-300 ">lg:hover:-300 </div>
  <div class="lg:hover:delay-500 lg:hover:duration-500 ">lg:hover:-500 </div>
  <div class="lg:hover:delay-700 lg:hover:duration-700 ">lg:hover:-700 </div>
  <div class="lg:hover:delay-1000 lg:hover:duration-1000 ">lg:hover:-1000 </div>
  <div class="lg:active:delay-0 lg:active:duration-0 ">lg:active:-0 </div>
  <div class="lg:active:delay-75 lg:active:duration-75 ">lg:active:-75 </div>
  <div class="lg:active:delay-100 lg:active:duration-100 ">lg:active:-100 </div>
  <div class="lg:active:delay-150 lg:active:duration-150 ">lg:active:-150 </div>
  <div class="lg:active:delay-200 lg:active:duration-200 ">lg:active:-200 </div>
  <div class="lg:active:delay-300 lg:active:duration-300 ">lg:active:-300 </div>
  <div class="lg:active:delay-500 lg:active:duration-500 ">lg:active:-500 </div>
  <div class="lg:active:delay-700 lg:active:duration-700 ">lg:active:-700 </div>
  <div class="lg:active:delay-1000 lg:active:duration-1000 ">lg:active:-1000 </div>
  <div class="lg:focus:delay-0 lg:focus:duration-0 ">lg:focus:-0 </div>
  <div class="lg:focus:delay-75 lg:focus:duration-75 ">lg:focus:-75 </div>
  <div class="lg:focus:delay-100 lg:focus:duration-100 ">lg:focus:-100 </div>
  <div class="lg:focus:delay-150 lg:focus:duration-150 ">lg:focus:-150 </div>
  <div class="lg:focus:delay-200 lg:focus:duration-200 ">lg:focus:-200 </div>
  <div class="lg:focus:delay-300 lg:focus:duration-300 ">lg:focus:-300 </div>
  <div class="lg:focus:delay-500 lg:focus:duration-500 ">lg:focus:-500 </div>
  <div class="lg:focus:delay-700 lg:focus:duration-700 ">lg:focus:-700 </div>
  <div class="lg:focus:delay-1000 lg:focus:duration-1000 ">lg:focus:-1000 </div>
  <div class="xl:delay-0 xl:duration-0 ">xl:-0 </div>
  <div class="xl:delay-75 xl:duration-75 ">xl:-75 </div>
  <div class="xl:delay-100 xl:duration-100 ">xl:-100 </div>
  <div class="xl:delay-150 xl:duration-150 ">xl:-150 </div>
  <div class="xl:delay-200 xl:duration-200 ">xl:-200 </div>
  <div class="xl:delay-300 xl:duration-300 ">xl:-300 </div>
  <div class="xl:delay-500 xl:duration-500 ">xl:-500 </div>
  <div class="xl:delay-700 xl:duration-700 ">xl:-700 </div>
  <div class="xl:delay-1000 xl:duration-1000 ">xl:-1000 </div>
  <div class="xl:hover:delay-0 xl:hover:duration-0 ">xl:hover:-0 </div>
  <div class="xl:hover:delay-75 xl:hover:duration-75 ">xl:hover:-75 </div>
  <div class="xl:hover:delay-100 xl:hover:duration-100 ">xl:hover:-100 </div>
  <div class="xl:hover:delay-150 xl:hover:duration-150 ">xl:hover:-150 </div>
  <div class="xl:hover:delay-200 xl:hover:duration-200 ">xl:hover:-200 </div>
  <div class="xl:hover:delay-300 xl:hover:duration-300 ">xl:hover:-300 </div>
  <div class="xl:hover:delay-500 xl:hover:duration-500 ">xl:hover:-500 </div>
  <div class="xl:hover:delay-700 xl:hover:duration-700 ">xl:hover:-700 </div>
  <div class="xl:hover:delay-1000 xl:hover:duration-1000 ">xl:hover:-1000 </div>
  <div class="xl:active:delay-0 xl:active:duration-0 ">xl:active:-0 </div>
  <div class="xl:active:delay-75 xl:active:duration-75 ">xl:active:-75 </div>
  <div class="xl:active:delay-100 xl:active:duration-100 ">xl:active:-100 </div>
  <div class="xl:active:delay-150 xl:active:duration-150 ">xl:active:-150 </div>
  <div class="xl:active:delay-200 xl:active:duration-200 ">xl:active:-200 </div>
  <div class="xl:active:delay-300 xl:active:duration-300 ">xl:active:-300 </div>
  <div class="xl:active:delay-500 xl:active:duration-500 ">xl:active:-500 </div>
  <div class="xl:active:delay-700 xl:active:duration-700 ">xl:active:-700 </div>
  <div class="xl:active:delay-1000 xl:active:duration-1000 ">xl:active:-1000 </div>
  <div class="xl:focus:delay-0 xl:focus:duration-0 ">xl:focus:-0 </div>
  <div class="xl:focus:delay-75 xl:focus:duration-75 ">xl:focus:-75 </div>
  <div class="xl:focus:delay-100 xl:focus:duration-100 ">xl:focus:-100 </div>
  <div class="xl:focus:delay-150 xl:focus:duration-150 ">xl:focus:-150 </div>
  <div class="xl:focus:delay-200 xl:focus:duration-200 ">xl:focus:-200 </div>
  <div class="xl:focus:delay-300 xl:focus:duration-300 ">xl:focus:-300 </div>
  <div class="xl:focus:delay-500 xl:focus:duration-500 ">xl:focus:-500 </div>
  <div class="xl:focus:delay-700 xl:focus:duration-700 ">xl:focus:-700 </div>
  <div class="xl:focus:delay-1000 xl:focus:duration-1000 ">xl:focus:-1000 </div>
  <div class="dark:delay-0 dark:duration-0 ">dark:-0 </div>
  <div class="dark:delay-75 dark:duration-75 ">dark:-75 </div>
  <div class="dark:delay-100 dark:duration-100 ">dark:-100 </div>
  <div class="dark:delay-150 dark:duration-150 ">dark:-150 </div>
  <div class="dark:delay-200 dark:duration-200 ">dark:-200 </div>
  <div class="dark:delay-300 dark:duration-300 ">dark:-300 </div>
  <div class="dark:delay-500 dark:duration-500 ">dark:-500 </div>
  <div class="dark:delay-700 dark:duration-700 ">dark:-700 </div>
  <div class="dark:delay-1000 dark:duration-1000 ">dark:-1000 </div>
  <div class="dark:hover:delay-0 dark:hover:duration-0 ">dark:hover:-0 </div>
  <div class="dark:hover:delay-75 dark:hover:duration-75 ">dark:hover:-75 </div>
  <div class="dark:hover:delay-100 dark:hover:duration-100 ">dark:hover:-100 </div>
  <div class="dark:hover:delay-150 dark:hover:duration-150 ">dark:hover:-150 </div>
  <div class="dark:hover:delay-200 dark:hover:duration-200 ">dark:hover:-200 </div>
  <div class="dark:hover:delay-300 dark:hover:duration-300 ">dark:hover:-300 </div>
  <div class="dark:hover:delay-500 dark:hover:duration-500 ">dark:hover:-500 </div>
  <div class="dark:hover:delay-700 dark:hover:duration-700 ">dark:hover:-700 </div>
  <div class="dark:hover:delay-1000 dark:hover:duration-1000 ">dark:hover:-1000 </div>
  <div class="dark:active:delay-0 dark:active:duration-0 ">dark:active:-0 </div>
  <div class="dark:active:delay-75 dark:active:duration-75 ">dark:active:-75 </div>
  <div class="dark:active:delay-100 dark:active:duration-100 ">dark:active:-100 </div>
  <div class="dark:active:delay-150 dark:active:duration-150 ">dark:active:-150 </div>
  <div class="dark:active:delay-200 dark:active:duration-200 ">dark:active:-200 </div>
  <div class="dark:active:delay-300 dark:active:duration-300 ">dark:active:-300 </div>
  <div class="dark:active:delay-500 dark:active:duration-500 ">dark:active:-500 </div>
  <div class="dark:active:delay-700 dark:active:duration-700 ">dark:active:-700 </div>
  <div class="dark:active:delay-1000 dark:active:duration-1000 ">dark:active:-1000 </div>
  <div class="dark:focus:delay-0 dark:focus:duration-0 ">dark:focus:-0 </div>
  <div class="dark:focus:delay-75 dark:focus:duration-75 ">dark:focus:-75 </div>
  <div class="dark:focus:delay-100 dark:focus:duration-100 ">dark:focus:-100 </div>
  <div class="dark:focus:delay-150 dark:focus:duration-150 ">dark:focus:-150 </div>
  <div class="dark:focus:delay-200 dark:focus:duration-200 ">dark:focus:-200 </div>
  <div class="dark:focus:delay-300 dark:focus:duration-300 ">dark:focus:-300 </div>
  <div class="dark:focus:delay-500 dark:focus:duration-500 ">dark:focus:-500 </div>
  <div class="dark:focus:delay-700 dark:focus:duration-700 ">dark:focus:-700 </div>
  <div class="dark:focus:delay-1000 dark:focus:duration-1000 ">dark:focus:-1000 </div>
  <div class="dark:sm:delay-0 dark:sm:duration-0 ">dark:sm:-0 </div>
  <div class="dark:sm:delay-75 dark:sm:duration-75 ">dark:sm:-75 </div>
  <div class="dark:sm:delay-100 dark:sm:duration-100 ">dark:sm:-100 </div>
  <div class="dark:sm:delay-150 dark:sm:duration-150 ">dark:sm:-150 </div>
  <div class="dark:sm:delay-200 dark:sm:duration-200 ">dark:sm:-200 </div>
  <div class="dark:sm:delay-300 dark:sm:duration-300 ">dark:sm:-300 </div>
  <div class="dark:sm:delay-500 dark:sm:duration-500 ">dark:sm:-500 </div>
  <div class="dark:sm:delay-700 dark:sm:duration-700 ">dark:sm:-700 </div>
  <div class="dark:sm:delay-1000 dark:sm:duration-1000 ">dark:sm:-1000 </div>
  <div class="dark:sm:hover:delay-0 dark:sm:hover:duration-0 ">dark:sm:hover:-0 </div>
  <div class="dark:sm:hover:delay-75 dark:sm:hover:duration-75 ">dark:sm:hover:-75 </div>
  <div class="dark:sm:hover:delay-100 dark:sm:hover:duration-100 ">dark:sm:hover:-100 </div>
  <div class="dark:sm:hover:delay-150 dark:sm:hover:duration-150 ">dark:sm:hover:-150 </div>
  <div class="dark:sm:hover:delay-200 dark:sm:hover:duration-200 ">dark:sm:hover:-200 </div>
  <div class="dark:sm:hover:delay-300 dark:sm:hover:duration-300 ">dark:sm:hover:-300 </div>
  <div class="dark:sm:hover:delay-500 dark:sm:hover:duration-500 ">dark:sm:hover:-500 </div>
  <div class="dark:sm:hover:delay-700 dark:sm:hover:duration-700 ">dark:sm:hover:-700 </div>
  <div class="dark:sm:hover:delay-1000 dark:sm:hover:duration-1000 ">dark:sm:hover:-1000 </div>
  <div class="dark:sm:active:delay-0 dark:sm:active:duration-0 ">dark:sm:active:-0 </div>
  <div class="dark:sm:active:delay-75 dark:sm:active:duration-75 ">dark:sm:active:-75 </div>
  <div class="dark:sm:active:delay-100 dark:sm:active:duration-100 ">dark:sm:active:-100 </div>
  <div class="dark:sm:active:delay-150 dark:sm:active:duration-150 ">dark:sm:active:-150 </div>
  <div class="dark:sm:active:delay-200 dark:sm:active:duration-200 ">dark:sm:active:-200 </div>
  <div class="dark:sm:active:delay-300 dark:sm:active:duration-300 ">dark:sm:active:-300 </div>
  <div class="dark:sm:active:delay-500 dark:sm:active:duration-500 ">dark:sm:active:-500 </div>
  <div class="dark:sm:active:delay-700 dark:sm:active:duration-700 ">dark:sm:active:-700 </div>
  <div class="dark:sm:active:delay-1000 dark:sm:active:duration-1000 ">dark:sm:active:-1000 </div>
  <div class="dark:sm:focus:delay-0 dark:sm:focus:duration-0 ">dark:sm:focus:-0 </div>
  <div class="dark:sm:focus:delay-75 dark:sm:focus:duration-75 ">dark:sm:focus:-75 </div>
  <div class="dark:sm:focus:delay-100 dark:sm:focus:duration-100 ">dark:sm:focus:-100 </div>
  <div class="dark:sm:focus:delay-150 dark:sm:focus:duration-150 ">dark:sm:focus:-150 </div>
  <div class="dark:sm:focus:delay-200 dark:sm:focus:duration-200 ">dark:sm:focus:-200 </div>
  <div class="dark:sm:focus:delay-300 dark:sm:focus:duration-300 ">dark:sm:focus:-300 </div>
  <div class="dark:sm:focus:delay-500 dark:sm:focus:duration-500 ">dark:sm:focus:-500 </div>
  <div class="dark:sm:focus:delay-700 dark:sm:focus:duration-700 ">dark:sm:focus:-700 </div>
  <div class="dark:sm:focus:delay-1000 dark:sm:focus:duration-1000 ">dark:sm:focus:-1000 </div>
  <div class="dark:md:delay-0 dark:md:duration-0 ">dark:md:-0 </div>
  <div class="dark:md:delay-75 dark:md:duration-75 ">dark:md:-75 </div>
  <div class="dark:md:delay-100 dark:md:duration-100 ">dark:md:-100 </div>
  <div class="dark:md:delay-150 dark:md:duration-150 ">dark:md:-150 </div>
  <div class="dark:md:delay-200 dark:md:duration-200 ">dark:md:-200 </div>
  <div class="dark:md:delay-300 dark:md:duration-300 ">dark:md:-300 </div>
  <div class="dark:md:delay-500 dark:md:duration-500 ">dark:md:-500 </div>
  <div class="dark:md:delay-700 dark:md:duration-700 ">dark:md:-700 </div>
  <div class="dark:md:delay-1000 dark:md:duration-1000 ">dark:md:-1000 </div>
  <div class="dark:md:hover:delay-0 dark:md:hover:duration-0 ">dark:md:hover:-0 </div>
  <div class="dark:md:hover:delay-75 dark:md:hover:duration-75 ">dark:md:hover:-75 </div>
  <div class="dark:md:hover:delay-100 dark:md:hover:duration-100 ">dark:md:hover:-100 </div>
  <div class="dark:md:hover:delay-150 dark:md:hover:duration-150 ">dark:md:hover:-150 </div>
  <div class="dark:md:hover:delay-200 dark:md:hover:duration-200 ">dark:md:hover:-200 </div>
  <div class="dark:md:hover:delay-300 dark:md:hover:duration-300 ">dark:md:hover:-300 </div>
  <div class="dark:md:hover:delay-500 dark:md:hover:duration-500 ">dark:md:hover:-500 </div>
  <div class="dark:md:hover:delay-700 dark:md:hover:duration-700 ">dark:md:hover:-700 </div>
  <div class="dark:md:hover:delay-1000 dark:md:hover:duration-1000 ">dark:md:hover:-1000 </div>
  <div class="dark:md:active:delay-0 dark:md:active:duration-0 ">dark:md:active:-0 </div>
  <div class="dark:md:active:delay-75 dark:md:active:duration-75 ">dark:md:active:-75 </div>
  <div class="dark:md:active:delay-100 dark:md:active:duration-100 ">dark:md:active:-100 </div>
  <div class="dark:md:active:delay-150 dark:md:active:duration-150 ">dark:md:active:-150 </div>
  <div class="dark:md:active:delay-200 dark:md:active:duration-200 ">dark:md:active:-200 </div>
  <div class="dark:md:active:delay-300 dark:md:active:duration-300 ">dark:md:active:-300 </div>
  <div class="dark:md:active:delay-500 dark:md:active:duration-500 ">dark:md:active:-500 </div>
  <div class="dark:md:active:delay-700 dark:md:active:duration-700 ">dark:md:active:-700 </div>
  <div class="dark:md:active:delay-1000 dark:md:active:duration-1000 ">dark:md:active:-1000 </div>
  <div class="dark:md:focus:delay-0 dark:md:focus:duration-0 ">dark:md:focus:-0 </div>
  <div class="dark:md:focus:delay-75 dark:md:focus:duration-75 ">dark:md:focus:-75 </div>
  <div class="dark:md:focus:delay-100 dark:md:focus:duration-100 ">dark:md:focus:-100 </div>
  <div class="dark:md:focus:delay-150 dark:md:focus:duration-150 ">dark:md:focus:-150 </div>
  <div class="dark:md:focus:delay-200 dark:md:focus:duration-200 ">dark:md:focus:-200 </div>
  <div class="dark:md:focus:delay-300 dark:md:focus:duration-300 ">dark:md:focus:-300 </div>
  <div class="dark:md:focus:delay-500 dark:md:focus:duration-500 ">dark:md:focus:-500 </div>
  <div class="dark:md:focus:delay-700 dark:md:focus:duration-700 ">dark:md:focus:-700 </div>
  <div class="dark:md:focus:delay-1000 dark:md:focus:duration-1000 ">dark:md:focus:-1000 </div>
  <div class="dark:lg:delay-0 dark:lg:duration-0 ">dark:lg:-0 </div>
  <div class="dark:lg:delay-75 dark:lg:duration-75 ">dark:lg:-75 </div>
  <div class="dark:lg:delay-100 dark:lg:duration-100 ">dark:lg:-100 </div>
  <div class="dark:lg:delay-150 dark:lg:duration-150 ">dark:lg:-150 </div>
  <div class="dark:lg:delay-200 dark:lg:duration-200 ">dark:lg:-200 </div>
  <div class="dark:lg:delay-300 dark:lg:duration-300 ">dark:lg:-300 </div>
  <div class="dark:lg:delay-500 dark:lg:duration-500 ">dark:lg:-500 </div>
  <div class="dark:lg:delay-700 dark:lg:duration-700 ">dark:lg:-700 </div>
  <div class="dark:lg:delay-1000 dark:lg:duration-1000 ">dark:lg:-1000 </div>
  <div class="dark:lg:hover:delay-0 dark:lg:hover:duration-0 ">dark:lg:hover:-0 </div>
  <div class="dark:lg:hover:delay-75 dark:lg:hover:duration-75 ">dark:lg:hover:-75 </div>
  <div class="dark:lg:hover:delay-100 dark:lg:hover:duration-100 ">dark:lg:hover:-100 </div>
  <div class="dark:lg:hover:delay-150 dark:lg:hover:duration-150 ">dark:lg:hover:-150 </div>
  <div class="dark:lg:hover:delay-200 dark:lg:hover:duration-200 ">dark:lg:hover:-200 </div>
  <div class="dark:lg:hover:delay-300 dark:lg:hover:duration-300 ">dark:lg:hover:-300 </div>
  <div class="dark:lg:hover:delay-500 dark:lg:hover:duration-500 ">dark:lg:hover:-500 </div>
  <div class="dark:lg:hover:delay-700 dark:lg:hover:duration-700 ">dark:lg:hover:-700 </div>
  <div class="dark:lg:hover:delay-1000 dark:lg:hover:duration-1000 ">dark:lg:hover:-1000 </div>
  <div class="dark:lg:active:delay-0 dark:lg:active:duration-0 ">dark:lg:active:-0 </div>
  <div class="dark:lg:active:delay-75 dark:lg:active:duration-75 ">dark:lg:active:-75 </div>
  <div class="dark:lg:active:delay-100 dark:lg:active:duration-100 ">dark:lg:active:-100 </div>
  <div class="dark:lg:active:delay-150 dark:lg:active:duration-150 ">dark:lg:active:-150 </div>
  <div class="dark:lg:active:delay-200 dark:lg:active:duration-200 ">dark:lg:active:-200 </div>
  <div class="dark:lg:active:delay-300 dark:lg:active:duration-300 ">dark:lg:active:-300 </div>
  <div class="dark:lg:active:delay-500 dark:lg:active:duration-500 ">dark:lg:active:-500 </div>
  <div class="dark:lg:active:delay-700 dark:lg:active:duration-700 ">dark:lg:active:-700 </div>
  <div class="dark:lg:active:delay-1000 dark:lg:active:duration-1000 ">dark:lg:active:-1000 </div>
  <div class="dark:lg:focus:delay-0 dark:lg:focus:duration-0 ">dark:lg:focus:-0 </div>
  <div class="dark:lg:focus:delay-75 dark:lg:focus:duration-75 ">dark:lg:focus:-75 </div>
  <div class="dark:lg:focus:delay-100 dark:lg:focus:duration-100 ">dark:lg:focus:-100 </div>
  <div class="dark:lg:focus:delay-150 dark:lg:focus:duration-150 ">dark:lg:focus:-150 </div>
  <div class="dark:lg:focus:delay-200 dark:lg:focus:duration-200 ">dark:lg:focus:-200 </div>
  <div class="dark:lg:focus:delay-300 dark:lg:focus:duration-300 ">dark:lg:focus:-300 </div>
  <div class="dark:lg:focus:delay-500 dark:lg:focus:duration-500 ">dark:lg:focus:-500 </div>
  <div class="dark:lg:focus:delay-700 dark:lg:focus:duration-700 ">dark:lg:focus:-700 </div>
  <div class="dark:lg:focus:delay-1000 dark:lg:focus:duration-1000 ">dark:lg:focus:-1000 </div>
  <div class="dark:xl:delay-0 dark:xl:duration-0 ">dark:xl:-0 </div>
  <div class="dark:xl:delay-75 dark:xl:duration-75 ">dark:xl:-75 </div>
  <div class="dark:xl:delay-100 dark:xl:duration-100 ">dark:xl:-100 </div>
  <div class="dark:xl:delay-150 dark:xl:duration-150 ">dark:xl:-150 </div>
  <div class="dark:xl:delay-200 dark:xl:duration-200 ">dark:xl:-200 </div>
  <div class="dark:xl:delay-300 dark:xl:duration-300 ">dark:xl:-300 </div>
  <div class="dark:xl:delay-500 dark:xl:duration-500 ">dark:xl:-500 </div>
  <div class="dark:xl:delay-700 dark:xl:duration-700 ">dark:xl:-700 </div>
  <div class="dark:xl:delay-1000 dark:xl:duration-1000 ">dark:xl:-1000 </div>
  <div class="dark:xl:hover:delay-0 dark:xl:hover:duration-0 ">dark:xl:hover:-0 </div>
  <div class="dark:xl:hover:delay-75 dark:xl:hover:duration-75 ">dark:xl:hover:-75 </div>
  <div class="dark:xl:hover:delay-100 dark:xl:hover:duration-100 ">dark:xl:hover:-100 </div>
  <div class="dark:xl:hover:delay-150 dark:xl:hover:duration-150 ">dark:xl:hover:-150 </div>
  <div class="dark:xl:hover:delay-200 dark:xl:hover:duration-200 ">dark:xl:hover:-200 </div>
  <div class="dark:xl:hover:delay-300 dark:xl:hover:duration-300 ">dark:xl:hover:-300 </div>
  <div class="dark:xl:hover:delay-500 dark:xl:hover:duration-500 ">dark:xl:hover:-500 </div>
  <div class="dark:xl:hover:delay-700 dark:xl:hover:duration-700 ">dark:xl:hover:-700 </div>
  <div class="dark:xl:hover:delay-1000 dark:xl:hover:duration-1000 ">dark:xl:hover:-1000 </div>
  <div class="dark:xl:active:delay-0 dark:xl:active:duration-0 ">dark:xl:active:-0 </div>
  <div class="dark:xl:active:delay-75 dark:xl:active:duration-75 ">dark:xl:active:-75 </div>
  <div class="dark:xl:active:delay-100 dark:xl:active:duration-100 ">dark:xl:active:-100 </div>
  <div class="dark:xl:active:delay-150 dark:xl:active:duration-150 ">dark:xl:active:-150 </div>
  <div class="dark:xl:active:delay-200 dark:xl:active:duration-200 ">dark:xl:active:-200 </div>
  <div class="dark:xl:active:delay-300 dark:xl:active:duration-300 ">dark:xl:active:-300 </div>
  <div class="dark:xl:active:delay-500 dark:xl:active:duration-500 ">dark:xl:active:-500 </div>
  <div class="dark:xl:active:delay-700 dark:xl:active:duration-700 ">dark:xl:active:-700 </div>
  <div class="dark:xl:active:delay-1000 dark:xl:active:duration-1000 ">dark:xl:active:-1000 </div>
  <div class="dark:xl:focus:delay-0 dark:xl:focus:duration-0 ">dark:xl:focus:-0 </div>
  <div class="dark:xl:focus:delay-75 dark:xl:focus:duration-75 ">dark:xl:focus:-75 </div>
  <div class="dark:xl:focus:delay-100 dark:xl:focus:duration-100 ">dark:xl:focus:-100 </div>
  <div class="dark:xl:focus:delay-150 dark:xl:focus:duration-150 ">dark:xl:focus:-150 </div>
  <div class="dark:xl:focus:delay-200 dark:xl:focus:duration-200 ">dark:xl:focus:-200 </div>
  <div class="dark:xl:focus:delay-300 dark:xl:focus:duration-300 ">dark:xl:focus:-300 </div>
  <div class="dark:xl:focus:delay-500 dark:xl:focus:duration-500 ">dark:xl:focus:-500 </div>
  <div class="dark:xl:focus:delay-700 dark:xl:focus:duration-700 ">dark:xl:focus:-700 </div>
  <div class="dark:xl:focus:delay-1000 dark:xl:focus:duration-1000 ">dark:xl:focus:-1000 </div>
  <div class="ease-linear ">-linear </div>
  <div class="ease-in ">-in </div>
  <div class="ease-out ">-out </div>
  <div class="ease-in-out ">-in-out </div>
  <div class="hover:ease-linear ">hover:-linear </div>
  <div class="hover:ease-in ">hover:-in </div>
  <div class="hover:ease-out ">hover:-out </div>
  <div class="hover:ease-in-out ">hover:-in-out </div>
  <div class="active:ease-linear ">active:-linear </div>
  <div class="active:ease-in ">active:-in </div>
  <div class="active:ease-out ">active:-out </div>
  <div class="active:ease-in-out ">active:-in-out </div>
  <div class="focus:ease-linear ">focus:-linear </div>
  <div class="focus:ease-in ">focus:-in </div>
  <div class="focus:ease-out ">focus:-out </div>
  <div class="focus:ease-in-out ">focus:-in-out </div>
  <div class="sm:ease-linear ">sm:-linear </div>
  <div class="sm:ease-in ">sm:-in </div>
  <div class="sm:ease-out ">sm:-out </div>
  <div class="sm:ease-in-out ">sm:-in-out </div>
  <div class="sm:hover:ease-linear ">sm:hover:-linear </div>
  <div class="sm:hover:ease-in ">sm:hover:-in </div>
  <div class="sm:hover:ease-out ">sm:hover:-out </div>
  <div class="sm:hover:ease-in-out ">sm:hover:-in-out </div>
  <div class="sm:active:ease-linear ">sm:active:-linear </div>
  <div class="sm:active:ease-in ">sm:active:-in </div>
  <div class="sm:active:ease-out ">sm:active:-out </div>
  <div class="sm:active:ease-in-out ">sm:active:-in-out </div>
  <div class="sm:focus:ease-linear ">sm:focus:-linear </div>
  <div class="sm:focus:ease-in ">sm:focus:-in </div>
  <div class="sm:focus:ease-out ">sm:focus:-out </div>
  <div class="sm:focus:ease-in-out ">sm:focus:-in-out </div>
  <div class="md:ease-linear ">md:-linear </div>
  <div class="md:ease-in ">md:-in </div>
  <div class="md:ease-out ">md:-out </div>
  <div class="md:ease-in-out ">md:-in-out </div>
  <div class="md:hover:ease-linear ">md:hover:-linear </div>
  <div class="md:hover:ease-in ">md:hover:-in </div>
  <div class="md:hover:ease-out ">md:hover:-out </div>
  <div class="md:hover:ease-in-out ">md:hover:-in-out </div>
  <div class="md:active:ease-linear ">md:active:-linear </div>
  <div class="md:active:ease-in ">md:active:-in </div>
  <div class="md:active:ease-out ">md:active:-out </div>
  <div class="md:active:ease-in-out ">md:active:-in-out </div>
  <div class="md:focus:ease-linear ">md:focus:-linear </div>
  <div class="md:focus:ease-in ">md:focus:-in </div>
  <div class="md:focus:ease-out ">md:focus:-out </div>
  <div class="md:focus:ease-in-out ">md:focus:-in-out </div>
  <div class="lg:ease-linear ">lg:-linear </div>
  <div class="lg:ease-in ">lg:-in </div>
  <div class="lg:ease-out ">lg:-out </div>
  <div class="lg:ease-in-out ">lg:-in-out </div>
  <div class="lg:hover:ease-linear ">lg:hover:-linear </div>
  <div class="lg:hover:ease-in ">lg:hover:-in </div>
  <div class="lg:hover:ease-out ">lg:hover:-out </div>
  <div class="lg:hover:ease-in-out ">lg:hover:-in-out </div>
  <div class="lg:active:ease-linear ">lg:active:-linear </div>
  <div class="lg:active:ease-in ">lg:active:-in </div>
  <div class="lg:active:ease-out ">lg:active:-out </div>
  <div class="lg:active:ease-in-out ">lg:active:-in-out </div>
  <div class="lg:focus:ease-linear ">lg:focus:-linear </div>
  <div class="lg:focus:ease-in ">lg:focus:-in </div>
  <div class="lg:focus:ease-out ">lg:focus:-out </div>
  <div class="lg:focus:ease-in-out ">lg:focus:-in-out </div>
  <div class="xl:ease-linear ">xl:-linear </div>
  <div class="xl:ease-in ">xl:-in </div>
  <div class="xl:ease-out ">xl:-out </div>
  <div class="xl:ease-in-out ">xl:-in-out </div>
  <div class="xl:hover:ease-linear ">xl:hover:-linear </div>
  <div class="xl:hover:ease-in ">xl:hover:-in </div>
  <div class="xl:hover:ease-out ">xl:hover:-out </div>
  <div class="xl:hover:ease-in-out ">xl:hover:-in-out </div>
  <div class="xl:active:ease-linear ">xl:active:-linear </div>
  <div class="xl:active:ease-in ">xl:active:-in </div>
  <div class="xl:active:ease-out ">xl:active:-out </div>
  <div class="xl:active:ease-in-out ">xl:active:-in-out </div>
  <div class="xl:focus:ease-linear ">xl:focus:-linear </div>
  <div class="xl:focus:ease-in ">xl:focus:-in </div>
  <div class="xl:focus:ease-out ">xl:focus:-out </div>
  <div class="xl:focus:ease-in-out ">xl:focus:-in-out </div>
  <div class="dark:ease-linear ">dark:-linear </div>
  <div class="dark:ease-in ">dark:-in </div>
  <div class="dark:ease-out ">dark:-out </div>
  <div class="dark:ease-in-out ">dark:-in-out </div>
  <div class="dark:hover:ease-linear ">dark:hover:-linear </div>
  <div class="dark:hover:ease-in ">dark:hover:-in </div>
  <div class="dark:hover:ease-out ">dark:hover:-out </div>
  <div class="dark:hover:ease-in-out ">dark:hover:-in-out </div>
  <div class="dark:active:ease-linear ">dark:active:-linear </div>
  <div class="dark:active:ease-in ">dark:active:-in </div>
  <div class="dark:active:ease-out ">dark:active:-out </div>
  <div class="dark:active:ease-in-out ">dark:active:-in-out </div>
  <div class="dark:focus:ease-linear ">dark:focus:-linear </div>
  <div class="dark:focus:ease-in ">dark:focus:-in </div>
  <div class="dark:focus:ease-out ">dark:focus:-out </div>
  <div class="dark:focus:ease-in-out ">dark:focus:-in-out </div>
  <div class="dark:sm:ease-linear ">dark:sm:-linear </div>
  <div class="dark:sm:ease-in ">dark:sm:-in </div>
  <div class="dark:sm:ease-out ">dark:sm:-out </div>
  <div class="dark:sm:ease-in-out ">dark:sm:-in-out </div>
  <div class="dark:sm:hover:ease-linear ">dark:sm:hover:-linear </div>
  <div class="dark:sm:hover:ease-in ">dark:sm:hover:-in </div>
  <div class="dark:sm:hover:ease-out ">dark:sm:hover:-out </div>
  <div class="dark:sm:hover:ease-in-out ">dark:sm:hover:-in-out </div>
  <div class="dark:sm:active:ease-linear ">dark:sm:active:-linear </div>
  <div class="dark:sm:active:ease-in ">dark:sm:active:-in </div>
  <div class="dark:sm:active:ease-out ">dark:sm:active:-out </div>
  <div class="dark:sm:active:ease-in-out ">dark:sm:active:-in-out </div>
  <div class="dark:sm:focus:ease-linear ">dark:sm:focus:-linear </div>
  <div class="dark:sm:focus:ease-in ">dark:sm:focus:-in </div>
  <div class="dark:sm:focus:ease-out ">dark:sm:focus:-out </div>
  <div class="dark:sm:focus:ease-in-out ">dark:sm:focus:-in-out </div>
  <div class="dark:md:ease-linear ">dark:md:-linear </div>
  <div class="dark:md:ease-in ">dark:md:-in </div>
  <div class="dark:md:ease-out ">dark:md:-out </div>
  <div class="dark:md:ease-in-out ">dark:md:-in-out </div>
  <div class="dark:md:hover:ease-linear ">dark:md:hover:-linear </div>
  <div class="dark:md:hover:ease-in ">dark:md:hover:-in </div>
  <div class="dark:md:hover:ease-out ">dark:md:hover:-out </div>
  <div class="dark:md:hover:ease-in-out ">dark:md:hover:-in-out </div>
  <div class="dark:md:active:ease-linear ">dark:md:active:-linear </div>
  <div class="dark:md:active:ease-in ">dark:md:active:-in </div>
  <div class="dark:md:active:ease-out ">dark:md:active:-out </div>
  <div class="dark:md:active:ease-in-out ">dark:md:active:-in-out </div>
  <div class="dark:md:focus:ease-linear ">dark:md:focus:-linear </div>
  <div class="dark:md:focus:ease-in ">dark:md:focus:-in </div>
  <div class="dark:md:focus:ease-out ">dark:md:focus:-out </div>
  <div class="dark:md:focus:ease-in-out ">dark:md:focus:-in-out </div>
  <div class="dark:lg:ease-linear ">dark:lg:-linear </div>
  <div class="dark:lg:ease-in ">dark:lg:-in </div>
  <div class="dark:lg:ease-out ">dark:lg:-out </div>
  <div class="dark:lg:ease-in-out ">dark:lg:-in-out </div>
  <div class="dark:lg:hover:ease-linear ">dark:lg:hover:-linear </div>
  <div class="dark:lg:hover:ease-in ">dark:lg:hover:-in </div>
  <div class="dark:lg:hover:ease-out ">dark:lg:hover:-out </div>
  <div class="dark:lg:hover:ease-in-out ">dark:lg:hover:-in-out </div>
  <div class="dark:lg:active:ease-linear ">dark:lg:active:-linear </div>
  <div class="dark:lg:active:ease-in ">dark:lg:active:-in </div>
  <div class="dark:lg:active:ease-out ">dark:lg:active:-out </div>
  <div class="dark:lg:active:ease-in-out ">dark:lg:active:-in-out </div>
  <div class="dark:lg:focus:ease-linear ">dark:lg:focus:-linear </div>
  <div class="dark:lg:focus:ease-in ">dark:lg:focus:-in </div>
  <div class="dark:lg:focus:ease-out ">dark:lg:focus:-out </div>
  <div class="dark:lg:focus:ease-in-out ">dark:lg:focus:-in-out </div>
  <div class="dark:xl:ease-linear ">dark:xl:-linear </div>
  <div class="dark:xl:ease-in ">dark:xl:-in </div>
  <div class="dark:xl:ease-out ">dark:xl:-out </div>
  <div class="dark:xl:ease-in-out ">dark:xl:-in-out </div>
  <div class="dark:xl:hover:ease-linear ">dark:xl:hover:-linear </div>
  <div class="dark:xl:hover:ease-in ">dark:xl:hover:-in </div>
  <div class="dark:xl:hover:ease-out ">dark:xl:hover:-out </div>
  <div class="dark:xl:hover:ease-in-out ">dark:xl:hover:-in-out </div>
  <div class="dark:xl:active:ease-linear ">dark:xl:active:-linear </div>
  <div class="dark:xl:active:ease-in ">dark:xl:active:-in </div>
  <div class="dark:xl:active:ease-out ">dark:xl:active:-out </div>
  <div class="dark:xl:active:ease-in-out ">dark:xl:active:-in-out </div>
  <div class="dark:xl:focus:ease-linear ">dark:xl:focus:-linear </div>
  <div class="dark:xl:focus:ease-in ">dark:xl:focus:-in </div>
  <div class="dark:xl:focus:ease-out ">dark:xl:focus:-out </div>
  <div class="dark:xl:focus:ease-in-out ">dark:xl:focus:-in-out </div>
  <div class="animate-none ">-none </div>
  <div class="animate-spin ">-spin </div>
  <div class="animate-ping ">-ping </div>
  <div class="animate-pulse ">-pulse </div>
  <div class="animate-bounce ">-bounce </div>
  <div class="hover:animate-none ">hover:-none </div>
  <div class="hover:animate-spin ">hover:-spin </div>
  <div class="hover:animate-ping ">hover:-ping </div>
  <div class="hover:animate-pulse ">hover:-pulse </div>
  <div class="hover:animate-bounce ">hover:-bounce </div>
  <div class="active:animate-none ">active:-none </div>
  <div class="active:animate-spin ">active:-spin </div>
  <div class="active:animate-ping ">active:-ping </div>
  <div class="active:animate-pulse ">active:-pulse </div>
  <div class="active:animate-bounce ">active:-bounce </div>
  <div class="focus:animate-none ">focus:-none </div>
  <div class="focus:animate-spin ">focus:-spin </div>
  <div class="focus:animate-ping ">focus:-ping </div>
  <div class="focus:animate-pulse ">focus:-pulse </div>
  <div class="focus:animate-bounce ">focus:-bounce </div>
  <div class="sm:animate-none ">sm:-none </div>
  <div class="sm:animate-spin ">sm:-spin </div>
  <div class="sm:animate-ping ">sm:-ping </div>
  <div class="sm:animate-pulse ">sm:-pulse </div>
  <div class="sm:animate-bounce ">sm:-bounce </div>
  <div class="sm:hover:animate-none ">sm:hover:-none </div>
  <div class="sm:hover:animate-spin ">sm:hover:-spin </div>
  <div class="sm:hover:animate-ping ">sm:hover:-ping </div>
  <div class="sm:hover:animate-pulse ">sm:hover:-pulse </div>
  <div class="sm:hover:animate-bounce ">sm:hover:-bounce </div>
  <div class="sm:active:animate-none ">sm:active:-none </div>
  <div class="sm:active:animate-spin ">sm:active:-spin </div>
  <div class="sm:active:animate-ping ">sm:active:-ping </div>
  <div class="sm:active:animate-pulse ">sm:active:-pulse </div>
  <div class="sm:active:animate-bounce ">sm:active:-bounce </div>
  <div class="sm:focus:animate-none ">sm:focus:-none </div>
  <div class="sm:focus:animate-spin ">sm:focus:-spin </div>
  <div class="sm:focus:animate-ping ">sm:focus:-ping </div>
  <div class="sm:focus:animate-pulse ">sm:focus:-pulse </div>
  <div class="sm:focus:animate-bounce ">sm:focus:-bounce </div>
  <div class="md:animate-none ">md:-none </div>
  <div class="md:animate-spin ">md:-spin </div>
  <div class="md:animate-ping ">md:-ping </div>
  <div class="md:animate-pulse ">md:-pulse </div>
  <div class="md:animate-bounce ">md:-bounce </div>
  <div class="md:hover:animate-none ">md:hover:-none </div>
  <div class="md:hover:animate-spin ">md:hover:-spin </div>
  <div class="md:hover:animate-ping ">md:hover:-ping </div>
  <div class="md:hover:animate-pulse ">md:hover:-pulse </div>
  <div class="md:hover:animate-bounce ">md:hover:-bounce </div>
  <div class="md:active:animate-none ">md:active:-none </div>
  <div class="md:active:animate-spin ">md:active:-spin </div>
  <div class="md:active:animate-ping ">md:active:-ping </div>
  <div class="md:active:animate-pulse ">md:active:-pulse </div>
  <div class="md:active:animate-bounce ">md:active:-bounce </div>
  <div class="md:focus:animate-none ">md:focus:-none </div>
  <div class="md:focus:animate-spin ">md:focus:-spin </div>
  <div class="md:focus:animate-ping ">md:focus:-ping </div>
  <div class="md:focus:animate-pulse ">md:focus:-pulse </div>
  <div class="md:focus:animate-bounce ">md:focus:-bounce </div>
  <div class="lg:animate-none ">lg:-none </div>
  <div class="lg:animate-spin ">lg:-spin </div>
  <div class="lg:animate-ping ">lg:-ping </div>
  <div class="lg:animate-pulse ">lg:-pulse </div>
  <div class="lg:animate-bounce ">lg:-bounce </div>
  <div class="lg:hover:animate-none ">lg:hover:-none </div>
  <div class="lg:hover:animate-spin ">lg:hover:-spin </div>
  <div class="lg:hover:animate-ping ">lg:hover:-ping </div>
  <div class="lg:hover:animate-pulse ">lg:hover:-pulse </div>
  <div class="lg:hover:animate-bounce ">lg:hover:-bounce </div>
  <div class="lg:active:animate-none ">lg:active:-none </div>
  <div class="lg:active:animate-spin ">lg:active:-spin </div>
  <div class="lg:active:animate-ping ">lg:active:-ping </div>
  <div class="lg:active:animate-pulse ">lg:active:-pulse </div>
  <div class="lg:active:animate-bounce ">lg:active:-bounce </div>
  <div class="lg:focus:animate-none ">lg:focus:-none </div>
  <div class="lg:focus:animate-spin ">lg:focus:-spin </div>
  <div class="lg:focus:animate-ping ">lg:focus:-ping </div>
  <div class="lg:focus:animate-pulse ">lg:focus:-pulse </div>
  <div class="lg:focus:animate-bounce ">lg:focus:-bounce </div>
  <div class="xl:animate-none ">xl:-none </div>
  <div class="xl:animate-spin ">xl:-spin </div>
  <div class="xl:animate-ping ">xl:-ping </div>
  <div class="xl:animate-pulse ">xl:-pulse </div>
  <div class="xl:animate-bounce ">xl:-bounce </div>
  <div class="xl:hover:animate-none ">xl:hover:-none </div>
  <div class="xl:hover:animate-spin ">xl:hover:-spin </div>
  <div class="xl:hover:animate-ping ">xl:hover:-ping </div>
  <div class="xl:hover:animate-pulse ">xl:hover:-pulse </div>
  <div class="xl:hover:animate-bounce ">xl:hover:-bounce </div>
  <div class="xl:active:animate-none ">xl:active:-none </div>
  <div class="xl:active:animate-spin ">xl:active:-spin </div>
  <div class="xl:active:animate-ping ">xl:active:-ping </div>
  <div class="xl:active:animate-pulse ">xl:active:-pulse </div>
  <div class="xl:active:animate-bounce ">xl:active:-bounce </div>
  <div class="xl:focus:animate-none ">xl:focus:-none </div>
  <div class="xl:focus:animate-spin ">xl:focus:-spin </div>
  <div class="xl:focus:animate-ping ">xl:focus:-ping </div>
  <div class="xl:focus:animate-pulse ">xl:focus:-pulse </div>
  <div class="xl:focus:animate-bounce ">xl:focus:-bounce </div>
  <div class="dark:animate-none ">dark:-none </div>
  <div class="dark:animate-spin ">dark:-spin </div>
  <div class="dark:animate-ping ">dark:-ping </div>
  <div class="dark:animate-pulse ">dark:-pulse </div>
  <div class="dark:animate-bounce ">dark:-bounce </div>
  <div class="dark:hover:animate-none ">dark:hover:-none </div>
  <div class="dark:hover:animate-spin ">dark:hover:-spin </div>
  <div class="dark:hover:animate-ping ">dark:hover:-ping </div>
  <div class="dark:hover:animate-pulse ">dark:hover:-pulse </div>
  <div class="dark:hover:animate-bounce ">dark:hover:-bounce </div>
  <div class="dark:active:animate-none ">dark:active:-none </div>
  <div class="dark:active:animate-spin ">dark:active:-spin </div>
  <div class="dark:active:animate-ping ">dark:active:-ping </div>
  <div class="dark:active:animate-pulse ">dark:active:-pulse </div>
  <div class="dark:active:animate-bounce ">dark:active:-bounce </div>
  <div class="dark:focus:animate-none ">dark:focus:-none </div>
  <div class="dark:focus:animate-spin ">dark:focus:-spin </div>
  <div class="dark:focus:animate-ping ">dark:focus:-ping </div>
  <div class="dark:focus:animate-pulse ">dark:focus:-pulse </div>
  <div class="dark:focus:animate-bounce ">dark:focus:-bounce </div>
  <div class="dark:sm:animate-none ">dark:sm:-none </div>
  <div class="dark:sm:animate-spin ">dark:sm:-spin </div>
  <div class="dark:sm:animate-ping ">dark:sm:-ping </div>
  <div class="dark:sm:animate-pulse ">dark:sm:-pulse </div>
  <div class="dark:sm:animate-bounce ">dark:sm:-bounce </div>
  <div class="dark:sm:hover:animate-none ">dark:sm:hover:-none </div>
  <div class="dark:sm:hover:animate-spin ">dark:sm:hover:-spin </div>
  <div class="dark:sm:hover:animate-ping ">dark:sm:hover:-ping </div>
  <div class="dark:sm:hover:animate-pulse ">dark:sm:hover:-pulse </div>
  <div class="dark:sm:hover:animate-bounce ">dark:sm:hover:-bounce </div>
  <div class="dark:sm:active:animate-none ">dark:sm:active:-none </div>
  <div class="dark:sm:active:animate-spin ">dark:sm:active:-spin </div>
  <div class="dark:sm:active:animate-ping ">dark:sm:active:-ping </div>
  <div class="dark:sm:active:animate-pulse ">dark:sm:active:-pulse </div>
  <div class="dark:sm:active:animate-bounce ">dark:sm:active:-bounce </div>
  <div class="dark:sm:focus:animate-none ">dark:sm:focus:-none </div>
  <div class="dark:sm:focus:animate-spin ">dark:sm:focus:-spin </div>
  <div class="dark:sm:focus:animate-ping ">dark:sm:focus:-ping </div>
  <div class="dark:sm:focus:animate-pulse ">dark:sm:focus:-pulse </div>
  <div class="dark:sm:focus:animate-bounce ">dark:sm:focus:-bounce </div>
  <div class="dark:md:animate-none ">dark:md:-none </div>
  <div class="dark:md:animate-spin ">dark:md:-spin </div>
  <div class="dark:md:animate-ping ">dark:md:-ping </div>
  <div class="dark:md:animate-pulse ">dark:md:-pulse </div>
  <div class="dark:md:animate-bounce ">dark:md:-bounce </div>
  <div class="dark:md:hover:animate-none ">dark:md:hover:-none </div>
  <div class="dark:md:hover:animate-spin ">dark:md:hover:-spin </div>
  <div class="dark:md:hover:animate-ping ">dark:md:hover:-ping </div>
  <div class="dark:md:hover:animate-pulse ">dark:md:hover:-pulse </div>
  <div class="dark:md:hover:animate-bounce ">dark:md:hover:-bounce </div>
  <div class="dark:md:active:animate-none ">dark:md:active:-none </div>
  <div class="dark:md:active:animate-spin ">dark:md:active:-spin </div>
  <div class="dark:md:active:animate-ping ">dark:md:active:-ping </div>
  <div class="dark:md:active:animate-pulse ">dark:md:active:-pulse </div>
  <div class="dark:md:active:animate-bounce ">dark:md:active:-bounce </div>
  <div class="dark:md:focus:animate-none ">dark:md:focus:-none </div>
  <div class="dark:md:focus:animate-spin ">dark:md:focus:-spin </div>
  <div class="dark:md:focus:animate-ping ">dark:md:focus:-ping </div>
  <div class="dark:md:focus:animate-pulse ">dark:md:focus:-pulse </div>
  <div class="dark:md:focus:animate-bounce ">dark:md:focus:-bounce </div>
  <div class="dark:lg:animate-none ">dark:lg:-none </div>
  <div class="dark:lg:animate-spin ">dark:lg:-spin </div>
  <div class="dark:lg:animate-ping ">dark:lg:-ping </div>
  <div class="dark:lg:animate-pulse ">dark:lg:-pulse </div>
  <div class="dark:lg:animate-bounce ">dark:lg:-bounce </div>
  <div class="dark:lg:hover:animate-none ">dark:lg:hover:-none </div>
  <div class="dark:lg:hover:animate-spin ">dark:lg:hover:-spin </div>
  <div class="dark:lg:hover:animate-ping ">dark:lg:hover:-ping </div>
  <div class="dark:lg:hover:animate-pulse ">dark:lg:hover:-pulse </div>
  <div class="dark:lg:hover:animate-bounce ">dark:lg:hover:-bounce </div>
  <div class="dark:lg:active:animate-none ">dark:lg:active:-none </div>
  <div class="dark:lg:active:animate-spin ">dark:lg:active:-spin </div>
  <div class="dark:lg:active:animate-ping ">dark:lg:active:-ping </div>
  <div class="dark:lg:active:animate-pulse ">dark:lg:active:-pulse </div>
  <div class="dark:lg:active:animate-bounce ">dark:lg:active:-bounce </div>
  <div class="dark:lg:focus:animate-none ">dark:lg:focus:-none </div>
  <div class="dark:lg:focus:animate-spin ">dark:lg:focus:-spin </div>
  <div class="dark:lg:focus:animate-ping ">dark:lg:focus:-ping </div>
  <div class="dark:lg:focus:animate-pulse ">dark:lg:focus:-pulse </div>
  <div class="dark:lg:focus:animate-bounce ">dark:lg:focus:-bounce </div>
  <div class="dark:xl:animate-none ">dark:xl:-none </div>
  <div class="dark:xl:animate-spin ">dark:xl:-spin </div>
  <div class="dark:xl:animate-ping ">dark:xl:-ping </div>
  <div class="dark:xl:animate-pulse ">dark:xl:-pulse </div>
  <div class="dark:xl:animate-bounce ">dark:xl:-bounce </div>
  <div class="dark:xl:hover:animate-none ">dark:xl:hover:-none </div>
  <div class="dark:xl:hover:animate-spin ">dark:xl:hover:-spin </div>
  <div class="dark:xl:hover:animate-ping ">dark:xl:hover:-ping </div>
  <div class="dark:xl:hover:animate-pulse ">dark:xl:hover:-pulse </div>
  <div class="dark:xl:hover:animate-bounce ">dark:xl:hover:-bounce </div>
  <div class="dark:xl:active:animate-none ">dark:xl:active:-none </div>
  <div class="dark:xl:active:animate-spin ">dark:xl:active:-spin </div>
  <div class="dark:xl:active:animate-ping ">dark:xl:active:-ping </div>
  <div class="dark:xl:active:animate-pulse ">dark:xl:active:-pulse </div>
  <div class="dark:xl:active:animate-bounce ">dark:xl:active:-bounce </div>
  <div class="dark:xl:focus:animate-none ">dark:xl:focus:-none </div>
  <div class="dark:xl:focus:animate-spin ">dark:xl:focus:-spin </div>
  <div class="dark:xl:focus:animate-ping ">dark:xl:focus:-ping </div>
  <div class="dark:xl:focus:animate-pulse ">dark:xl:focus:-pulse </div>
  <div class="dark:xl:focus:animate-bounce ">dark:xl:focus:-bounce </div>

</template>
