<template>
  <div class="bg-transparent/70 text-transparent/70 shadow-transparent/70 border-transparent/70 divide-transparent/70 ring-transparent/70 outline-transparent/70 from-transparent/70 via-transparent/70 to-transparent/70 fill-transparent/70 accent-transparent/70  ">-transparent </div>
  <div class="bg-white/70 text-white/70 shadow-white/70 border-white/70 divide-white/70 ring-white/70 outline-white/70 from-white/70 via-white/70 to-white/70 fill-white/70 accent-white/70  ">-white </div>
  <div class="bg-black/70 text-black/70 shadow-black/70 border-black/70 divide-black/70 ring-black/70 outline-black/70 from-black/70 via-black/70 to-black/70 fill-black/70 accent-black/70  ">-black </div>
  <div class="bg-inherit/70 text-inherit/70 shadow-inherit/70 border-inherit/70 divide-inherit/70 ring-inherit/70 outline-inherit/70 from-inherit/70 via-inherit/70 to-inherit/70 fill-inherit/70 accent-inherit/70  ">-inherit </div>
  <div class="bg-current/70 text-current/70 shadow-current/70 border-current/70 divide-current/70 ring-current/70 outline-current/70 from-current/70 via-current/70 to-current/70 fill-current/70 accent-current/70  ">-current </div>
  <div class="hover:bg-transparent/70 hover:text-transparent/70 hover:shadow-transparent/70 hover:border-transparent/70 hover:divide-transparent/70 hover:ring-transparent/70 hover:outline-transparent/70 hover:from-transparent/70 hover:via-transparent/70 hover:to-transparent/70 hover:fill-transparent/70 hover:accent-transparent/70  ">hover:-transparent </div>
  <div class="hover:bg-white/70 hover:text-white/70 hover:shadow-white/70 hover:border-white/70 hover:divide-white/70 hover:ring-white/70 hover:outline-white/70 hover:from-white/70 hover:via-white/70 hover:to-white/70 hover:fill-white/70 hover:accent-white/70  ">hover:-white </div>
  <div class="hover:bg-black/70 hover:text-black/70 hover:shadow-black/70 hover:border-black/70 hover:divide-black/70 hover:ring-black/70 hover:outline-black/70 hover:from-black/70 hover:via-black/70 hover:to-black/70 hover:fill-black/70 hover:accent-black/70  ">hover:-black </div>
  <div class="hover:bg-inherit/70 hover:text-inherit/70 hover:shadow-inherit/70 hover:border-inherit/70 hover:divide-inherit/70 hover:ring-inherit/70 hover:outline-inherit/70 hover:from-inherit/70 hover:via-inherit/70 hover:to-inherit/70 hover:fill-inherit/70 hover:accent-inherit/70  ">hover:-inherit </div>
  <div class="hover:bg-current/70 hover:text-current/70 hover:shadow-current/70 hover:border-current/70 hover:divide-current/70 hover:ring-current/70 hover:outline-current/70 hover:from-current/70 hover:via-current/70 hover:to-current/70 hover:fill-current/70 hover:accent-current/70  ">hover:-current </div>
  <div class="active:bg-transparent/70 active:text-transparent/70 active:shadow-transparent/70 active:border-transparent/70 active:divide-transparent/70 active:ring-transparent/70 active:outline-transparent/70 active:from-transparent/70 active:via-transparent/70 active:to-transparent/70 active:fill-transparent/70 active:accent-transparent/70  ">active:-transparent </div>
  <div class="active:bg-white/70 active:text-white/70 active:shadow-white/70 active:border-white/70 active:divide-white/70 active:ring-white/70 active:outline-white/70 active:from-white/70 active:via-white/70 active:to-white/70 active:fill-white/70 active:accent-white/70  ">active:-white </div>
  <div class="active:bg-black/70 active:text-black/70 active:shadow-black/70 active:border-black/70 active:divide-black/70 active:ring-black/70 active:outline-black/70 active:from-black/70 active:via-black/70 active:to-black/70 active:fill-black/70 active:accent-black/70  ">active:-black </div>
  <div class="active:bg-inherit/70 active:text-inherit/70 active:shadow-inherit/70 active:border-inherit/70 active:divide-inherit/70 active:ring-inherit/70 active:outline-inherit/70 active:from-inherit/70 active:via-inherit/70 active:to-inherit/70 active:fill-inherit/70 active:accent-inherit/70  ">active:-inherit </div>
  <div class="active:bg-current/70 active:text-current/70 active:shadow-current/70 active:border-current/70 active:divide-current/70 active:ring-current/70 active:outline-current/70 active:from-current/70 active:via-current/70 active:to-current/70 active:fill-current/70 active:accent-current/70  ">active:-current </div>
  <div class="focus:bg-transparent/70 focus:text-transparent/70 focus:shadow-transparent/70 focus:border-transparent/70 focus:divide-transparent/70 focus:ring-transparent/70 focus:outline-transparent/70 focus:from-transparent/70 focus:via-transparent/70 focus:to-transparent/70 focus:fill-transparent/70 focus:accent-transparent/70  ">focus:-transparent </div>
  <div class="focus:bg-white/70 focus:text-white/70 focus:shadow-white/70 focus:border-white/70 focus:divide-white/70 focus:ring-white/70 focus:outline-white/70 focus:from-white/70 focus:via-white/70 focus:to-white/70 focus:fill-white/70 focus:accent-white/70  ">focus:-white </div>
  <div class="focus:bg-black/70 focus:text-black/70 focus:shadow-black/70 focus:border-black/70 focus:divide-black/70 focus:ring-black/70 focus:outline-black/70 focus:from-black/70 focus:via-black/70 focus:to-black/70 focus:fill-black/70 focus:accent-black/70  ">focus:-black </div>
  <div class="focus:bg-inherit/70 focus:text-inherit/70 focus:shadow-inherit/70 focus:border-inherit/70 focus:divide-inherit/70 focus:ring-inherit/70 focus:outline-inherit/70 focus:from-inherit/70 focus:via-inherit/70 focus:to-inherit/70 focus:fill-inherit/70 focus:accent-inherit/70  ">focus:-inherit </div>
  <div class="focus:bg-current/70 focus:text-current/70 focus:shadow-current/70 focus:border-current/70 focus:divide-current/70 focus:ring-current/70 focus:outline-current/70 focus:from-current/70 focus:via-current/70 focus:to-current/70 focus:fill-current/70 focus:accent-current/70  ">focus:-current </div>
  
  </template>