<template>
  <div class="bg-transparent/60 text-transparent/60 shadow-transparent/60 border-transparent/60 divide-transparent/60 ring-transparent/60 outline-transparent/60 from-transparent/60 via-transparent/60 to-transparent/60 fill-transparent/60 accent-transparent/60  ">-transparent </div>
  <div class="bg-white/60 text-white/60 shadow-white/60 border-white/60 divide-white/60 ring-white/60 outline-white/60 from-white/60 via-white/60 to-white/60 fill-white/60 accent-white/60  ">-white </div>
  <div class="bg-black/60 text-black/60 shadow-black/60 border-black/60 divide-black/60 ring-black/60 outline-black/60 from-black/60 via-black/60 to-black/60 fill-black/60 accent-black/60  ">-black </div>
  <div class="bg-inherit/60 text-inherit/60 shadow-inherit/60 border-inherit/60 divide-inherit/60 ring-inherit/60 outline-inherit/60 from-inherit/60 via-inherit/60 to-inherit/60 fill-inherit/60 accent-inherit/60  ">-inherit </div>
  <div class="bg-current/60 text-current/60 shadow-current/60 border-current/60 divide-current/60 ring-current/60 outline-current/60 from-current/60 via-current/60 to-current/60 fill-current/60 accent-current/60  ">-current </div>
  <div class="hover:bg-transparent/60 hover:text-transparent/60 hover:shadow-transparent/60 hover:border-transparent/60 hover:divide-transparent/60 hover:ring-transparent/60 hover:outline-transparent/60 hover:from-transparent/60 hover:via-transparent/60 hover:to-transparent/60 hover:fill-transparent/60 hover:accent-transparent/60  ">hover:-transparent </div>
  <div class="hover:bg-white/60 hover:text-white/60 hover:shadow-white/60 hover:border-white/60 hover:divide-white/60 hover:ring-white/60 hover:outline-white/60 hover:from-white/60 hover:via-white/60 hover:to-white/60 hover:fill-white/60 hover:accent-white/60  ">hover:-white </div>
  <div class="hover:bg-black/60 hover:text-black/60 hover:shadow-black/60 hover:border-black/60 hover:divide-black/60 hover:ring-black/60 hover:outline-black/60 hover:from-black/60 hover:via-black/60 hover:to-black/60 hover:fill-black/60 hover:accent-black/60  ">hover:-black </div>
  <div class="hover:bg-inherit/60 hover:text-inherit/60 hover:shadow-inherit/60 hover:border-inherit/60 hover:divide-inherit/60 hover:ring-inherit/60 hover:outline-inherit/60 hover:from-inherit/60 hover:via-inherit/60 hover:to-inherit/60 hover:fill-inherit/60 hover:accent-inherit/60  ">hover:-inherit </div>
  <div class="hover:bg-current/60 hover:text-current/60 hover:shadow-current/60 hover:border-current/60 hover:divide-current/60 hover:ring-current/60 hover:outline-current/60 hover:from-current/60 hover:via-current/60 hover:to-current/60 hover:fill-current/60 hover:accent-current/60  ">hover:-current </div>
  <div class="active:bg-transparent/60 active:text-transparent/60 active:shadow-transparent/60 active:border-transparent/60 active:divide-transparent/60 active:ring-transparent/60 active:outline-transparent/60 active:from-transparent/60 active:via-transparent/60 active:to-transparent/60 active:fill-transparent/60 active:accent-transparent/60  ">active:-transparent </div>
  <div class="active:bg-white/60 active:text-white/60 active:shadow-white/60 active:border-white/60 active:divide-white/60 active:ring-white/60 active:outline-white/60 active:from-white/60 active:via-white/60 active:to-white/60 active:fill-white/60 active:accent-white/60  ">active:-white </div>
  <div class="active:bg-black/60 active:text-black/60 active:shadow-black/60 active:border-black/60 active:divide-black/60 active:ring-black/60 active:outline-black/60 active:from-black/60 active:via-black/60 active:to-black/60 active:fill-black/60 active:accent-black/60  ">active:-black </div>
  <div class="active:bg-inherit/60 active:text-inherit/60 active:shadow-inherit/60 active:border-inherit/60 active:divide-inherit/60 active:ring-inherit/60 active:outline-inherit/60 active:from-inherit/60 active:via-inherit/60 active:to-inherit/60 active:fill-inherit/60 active:accent-inherit/60  ">active:-inherit </div>
  <div class="active:bg-current/60 active:text-current/60 active:shadow-current/60 active:border-current/60 active:divide-current/60 active:ring-current/60 active:outline-current/60 active:from-current/60 active:via-current/60 active:to-current/60 active:fill-current/60 active:accent-current/60  ">active:-current </div>
  <div class="focus:bg-transparent/60 focus:text-transparent/60 focus:shadow-transparent/60 focus:border-transparent/60 focus:divide-transparent/60 focus:ring-transparent/60 focus:outline-transparent/60 focus:from-transparent/60 focus:via-transparent/60 focus:to-transparent/60 focus:fill-transparent/60 focus:accent-transparent/60  ">focus:-transparent </div>
  <div class="focus:bg-white/60 focus:text-white/60 focus:shadow-white/60 focus:border-white/60 focus:divide-white/60 focus:ring-white/60 focus:outline-white/60 focus:from-white/60 focus:via-white/60 focus:to-white/60 focus:fill-white/60 focus:accent-white/60  ">focus:-white </div>
  <div class="focus:bg-black/60 focus:text-black/60 focus:shadow-black/60 focus:border-black/60 focus:divide-black/60 focus:ring-black/60 focus:outline-black/60 focus:from-black/60 focus:via-black/60 focus:to-black/60 focus:fill-black/60 focus:accent-black/60  ">focus:-black </div>
  <div class="focus:bg-inherit/60 focus:text-inherit/60 focus:shadow-inherit/60 focus:border-inherit/60 focus:divide-inherit/60 focus:ring-inherit/60 focus:outline-inherit/60 focus:from-inherit/60 focus:via-inherit/60 focus:to-inherit/60 focus:fill-inherit/60 focus:accent-inherit/60  ">focus:-inherit </div>
  <div class="focus:bg-current/60 focus:text-current/60 focus:shadow-current/60 focus:border-current/60 focus:divide-current/60 focus:ring-current/60 focus:outline-current/60 focus:from-current/60 focus:via-current/60 focus:to-current/60 focus:fill-current/60 focus:accent-current/60  ">focus:-current </div>
  
  </template>