<template>
  <div class="bg-transparent/40 text-transparent/40 shadow-transparent/40 border-transparent/40 divide-transparent/40 ring-transparent/40 outline-transparent/40 from-transparent/40 via-transparent/40 to-transparent/40 fill-transparent/40 accent-transparent/40  ">-transparent </div>
  <div class="bg-white/40 text-white/40 shadow-white/40 border-white/40 divide-white/40 ring-white/40 outline-white/40 from-white/40 via-white/40 to-white/40 fill-white/40 accent-white/40  ">-white </div>
  <div class="bg-black/40 text-black/40 shadow-black/40 border-black/40 divide-black/40 ring-black/40 outline-black/40 from-black/40 via-black/40 to-black/40 fill-black/40 accent-black/40  ">-black </div>
  <div class="bg-inherit/40 text-inherit/40 shadow-inherit/40 border-inherit/40 divide-inherit/40 ring-inherit/40 outline-inherit/40 from-inherit/40 via-inherit/40 to-inherit/40 fill-inherit/40 accent-inherit/40  ">-inherit </div>
  <div class="bg-current/40 text-current/40 shadow-current/40 border-current/40 divide-current/40 ring-current/40 outline-current/40 from-current/40 via-current/40 to-current/40 fill-current/40 accent-current/40  ">-current </div>
  <div class="hover:bg-transparent/40 hover:text-transparent/40 hover:shadow-transparent/40 hover:border-transparent/40 hover:divide-transparent/40 hover:ring-transparent/40 hover:outline-transparent/40 hover:from-transparent/40 hover:via-transparent/40 hover:to-transparent/40 hover:fill-transparent/40 hover:accent-transparent/40  ">hover:-transparent </div>
  <div class="hover:bg-white/40 hover:text-white/40 hover:shadow-white/40 hover:border-white/40 hover:divide-white/40 hover:ring-white/40 hover:outline-white/40 hover:from-white/40 hover:via-white/40 hover:to-white/40 hover:fill-white/40 hover:accent-white/40  ">hover:-white </div>
  <div class="hover:bg-black/40 hover:text-black/40 hover:shadow-black/40 hover:border-black/40 hover:divide-black/40 hover:ring-black/40 hover:outline-black/40 hover:from-black/40 hover:via-black/40 hover:to-black/40 hover:fill-black/40 hover:accent-black/40  ">hover:-black </div>
  <div class="hover:bg-inherit/40 hover:text-inherit/40 hover:shadow-inherit/40 hover:border-inherit/40 hover:divide-inherit/40 hover:ring-inherit/40 hover:outline-inherit/40 hover:from-inherit/40 hover:via-inherit/40 hover:to-inherit/40 hover:fill-inherit/40 hover:accent-inherit/40  ">hover:-inherit </div>
  <div class="hover:bg-current/40 hover:text-current/40 hover:shadow-current/40 hover:border-current/40 hover:divide-current/40 hover:ring-current/40 hover:outline-current/40 hover:from-current/40 hover:via-current/40 hover:to-current/40 hover:fill-current/40 hover:accent-current/40  ">hover:-current </div>
  <div class="active:bg-transparent/40 active:text-transparent/40 active:shadow-transparent/40 active:border-transparent/40 active:divide-transparent/40 active:ring-transparent/40 active:outline-transparent/40 active:from-transparent/40 active:via-transparent/40 active:to-transparent/40 active:fill-transparent/40 active:accent-transparent/40  ">active:-transparent </div>
  <div class="active:bg-white/40 active:text-white/40 active:shadow-white/40 active:border-white/40 active:divide-white/40 active:ring-white/40 active:outline-white/40 active:from-white/40 active:via-white/40 active:to-white/40 active:fill-white/40 active:accent-white/40  ">active:-white </div>
  <div class="active:bg-black/40 active:text-black/40 active:shadow-black/40 active:border-black/40 active:divide-black/40 active:ring-black/40 active:outline-black/40 active:from-black/40 active:via-black/40 active:to-black/40 active:fill-black/40 active:accent-black/40  ">active:-black </div>
  <div class="active:bg-inherit/40 active:text-inherit/40 active:shadow-inherit/40 active:border-inherit/40 active:divide-inherit/40 active:ring-inherit/40 active:outline-inherit/40 active:from-inherit/40 active:via-inherit/40 active:to-inherit/40 active:fill-inherit/40 active:accent-inherit/40  ">active:-inherit </div>
  <div class="active:bg-current/40 active:text-current/40 active:shadow-current/40 active:border-current/40 active:divide-current/40 active:ring-current/40 active:outline-current/40 active:from-current/40 active:via-current/40 active:to-current/40 active:fill-current/40 active:accent-current/40  ">active:-current </div>
  <div class="focus:bg-transparent/40 focus:text-transparent/40 focus:shadow-transparent/40 focus:border-transparent/40 focus:divide-transparent/40 focus:ring-transparent/40 focus:outline-transparent/40 focus:from-transparent/40 focus:via-transparent/40 focus:to-transparent/40 focus:fill-transparent/40 focus:accent-transparent/40  ">focus:-transparent </div>
  <div class="focus:bg-white/40 focus:text-white/40 focus:shadow-white/40 focus:border-white/40 focus:divide-white/40 focus:ring-white/40 focus:outline-white/40 focus:from-white/40 focus:via-white/40 focus:to-white/40 focus:fill-white/40 focus:accent-white/40  ">focus:-white </div>
  <div class="focus:bg-black/40 focus:text-black/40 focus:shadow-black/40 focus:border-black/40 focus:divide-black/40 focus:ring-black/40 focus:outline-black/40 focus:from-black/40 focus:via-black/40 focus:to-black/40 focus:fill-black/40 focus:accent-black/40  ">focus:-black </div>
  <div class="focus:bg-inherit/40 focus:text-inherit/40 focus:shadow-inherit/40 focus:border-inherit/40 focus:divide-inherit/40 focus:ring-inherit/40 focus:outline-inherit/40 focus:from-inherit/40 focus:via-inherit/40 focus:to-inherit/40 focus:fill-inherit/40 focus:accent-inherit/40  ">focus:-inherit </div>
  <div class="focus:bg-current/40 focus:text-current/40 focus:shadow-current/40 focus:border-current/40 focus:divide-current/40 focus:ring-current/40 focus:outline-current/40 focus:from-current/40 focus:via-current/40 focus:to-current/40 focus:fill-current/40 focus:accent-current/40  ">focus:-current </div>
  
  </template>