<template>
  <div class="bg-transparent/50 text-transparent/50 shadow-transparent/50 border-transparent/50 divide-transparent/50 ring-transparent/50 outline-transparent/50 from-transparent/50 via-transparent/50 to-transparent/50 fill-transparent/50 accent-transparent/50  ">-transparent </div>
  <div class="bg-white/50 text-white/50 shadow-white/50 border-white/50 divide-white/50 ring-white/50 outline-white/50 from-white/50 via-white/50 to-white/50 fill-white/50 accent-white/50  ">-white </div>
  <div class="bg-black/50 text-black/50 shadow-black/50 border-black/50 divide-black/50 ring-black/50 outline-black/50 from-black/50 via-black/50 to-black/50 fill-black/50 accent-black/50  ">-black </div>
  <div class="bg-inherit/50 text-inherit/50 shadow-inherit/50 border-inherit/50 divide-inherit/50 ring-inherit/50 outline-inherit/50 from-inherit/50 via-inherit/50 to-inherit/50 fill-inherit/50 accent-inherit/50  ">-inherit </div>
  <div class="bg-current/50 text-current/50 shadow-current/50 border-current/50 divide-current/50 ring-current/50 outline-current/50 from-current/50 via-current/50 to-current/50 fill-current/50 accent-current/50  ">-current </div>
  <div class="hover:bg-transparent/50 hover:text-transparent/50 hover:shadow-transparent/50 hover:border-transparent/50 hover:divide-transparent/50 hover:ring-transparent/50 hover:outline-transparent/50 hover:from-transparent/50 hover:via-transparent/50 hover:to-transparent/50 hover:fill-transparent/50 hover:accent-transparent/50  ">hover:-transparent </div>
  <div class="hover:bg-white/50 hover:text-white/50 hover:shadow-white/50 hover:border-white/50 hover:divide-white/50 hover:ring-white/50 hover:outline-white/50 hover:from-white/50 hover:via-white/50 hover:to-white/50 hover:fill-white/50 hover:accent-white/50  ">hover:-white </div>
  <div class="hover:bg-black/50 hover:text-black/50 hover:shadow-black/50 hover:border-black/50 hover:divide-black/50 hover:ring-black/50 hover:outline-black/50 hover:from-black/50 hover:via-black/50 hover:to-black/50 hover:fill-black/50 hover:accent-black/50  ">hover:-black </div>
  <div class="hover:bg-inherit/50 hover:text-inherit/50 hover:shadow-inherit/50 hover:border-inherit/50 hover:divide-inherit/50 hover:ring-inherit/50 hover:outline-inherit/50 hover:from-inherit/50 hover:via-inherit/50 hover:to-inherit/50 hover:fill-inherit/50 hover:accent-inherit/50  ">hover:-inherit </div>
  <div class="hover:bg-current/50 hover:text-current/50 hover:shadow-current/50 hover:border-current/50 hover:divide-current/50 hover:ring-current/50 hover:outline-current/50 hover:from-current/50 hover:via-current/50 hover:to-current/50 hover:fill-current/50 hover:accent-current/50  ">hover:-current </div>
  <div class="active:bg-transparent/50 active:text-transparent/50 active:shadow-transparent/50 active:border-transparent/50 active:divide-transparent/50 active:ring-transparent/50 active:outline-transparent/50 active:from-transparent/50 active:via-transparent/50 active:to-transparent/50 active:fill-transparent/50 active:accent-transparent/50  ">active:-transparent </div>
  <div class="active:bg-white/50 active:text-white/50 active:shadow-white/50 active:border-white/50 active:divide-white/50 active:ring-white/50 active:outline-white/50 active:from-white/50 active:via-white/50 active:to-white/50 active:fill-white/50 active:accent-white/50  ">active:-white </div>
  <div class="active:bg-black/50 active:text-black/50 active:shadow-black/50 active:border-black/50 active:divide-black/50 active:ring-black/50 active:outline-black/50 active:from-black/50 active:via-black/50 active:to-black/50 active:fill-black/50 active:accent-black/50  ">active:-black </div>
  <div class="active:bg-inherit/50 active:text-inherit/50 active:shadow-inherit/50 active:border-inherit/50 active:divide-inherit/50 active:ring-inherit/50 active:outline-inherit/50 active:from-inherit/50 active:via-inherit/50 active:to-inherit/50 active:fill-inherit/50 active:accent-inherit/50  ">active:-inherit </div>
  <div class="active:bg-current/50 active:text-current/50 active:shadow-current/50 active:border-current/50 active:divide-current/50 active:ring-current/50 active:outline-current/50 active:from-current/50 active:via-current/50 active:to-current/50 active:fill-current/50 active:accent-current/50  ">active:-current </div>
  <div class="focus:bg-transparent/50 focus:text-transparent/50 focus:shadow-transparent/50 focus:border-transparent/50 focus:divide-transparent/50 focus:ring-transparent/50 focus:outline-transparent/50 focus:from-transparent/50 focus:via-transparent/50 focus:to-transparent/50 focus:fill-transparent/50 focus:accent-transparent/50  ">focus:-transparent </div>
  <div class="focus:bg-white/50 focus:text-white/50 focus:shadow-white/50 focus:border-white/50 focus:divide-white/50 focus:ring-white/50 focus:outline-white/50 focus:from-white/50 focus:via-white/50 focus:to-white/50 focus:fill-white/50 focus:accent-white/50  ">focus:-white </div>
  <div class="focus:bg-black/50 focus:text-black/50 focus:shadow-black/50 focus:border-black/50 focus:divide-black/50 focus:ring-black/50 focus:outline-black/50 focus:from-black/50 focus:via-black/50 focus:to-black/50 focus:fill-black/50 focus:accent-black/50  ">focus:-black </div>
  <div class="focus:bg-inherit/50 focus:text-inherit/50 focus:shadow-inherit/50 focus:border-inherit/50 focus:divide-inherit/50 focus:ring-inherit/50 focus:outline-inherit/50 focus:from-inherit/50 focus:via-inherit/50 focus:to-inherit/50 focus:fill-inherit/50 focus:accent-inherit/50  ">focus:-inherit </div>
  <div class="focus:bg-current/50 focus:text-current/50 focus:shadow-current/50 focus:border-current/50 focus:divide-current/50 focus:ring-current/50 focus:outline-current/50 focus:from-current/50 focus:via-current/50 focus:to-current/50 focus:fill-current/50 focus:accent-current/50  ">focus:-current </div>
  
  </template>