@startuml
autoactivate on
actor user 
box Try Your Ideas
  participant TyiUI #cyan
  participant TyiAPI #cyan
  participant TyiService #cyan
end box
box Github
  participant GithubUI 
  participant GithubAPI 
end box
user -> TyiUI: SignIn Request Using Github
TyiUI -> GithubUI: Authentication request
return authentication code
TyiUI -> TyiAPI: signIn using Github
TyiAPI ->TyiService: sign in with github code
TyiService -> GithubAPI: get accessToken for code
return github accessToken
TyiService -> GithubAPI: get user data for github accessToken
return github user data
TyiService -> TyiService: Create User if new
TyiService -> TyiService: Create/Update User from Github data
return
return user
TyiService -> TyiService: Create accessToken for user
return accessToken
return accessToken
TyiAPI -> TyiAPI: Set session accessToken
return
TyiAPI -> TyiUI: Redirect user to main area
@enduml