@startuml
autoactivate on

box example box1
  actor Alice 
  participant BobWithLongName as bobby #cyan
end box

participant Royal <<comment>> [
    =Rey
    ----
    sin trono
]

box example box2
  boundary Boundary
  database MySql as dbs
  control Process as process
  collections Collection
  queue MyQueue
  participant test <<comment>>
end box
  
Alice -[#red]> bobby: Authentication Request
note over bobby : initial state of Bobby
return Authentication Response
== alternative example ==

alt successfull case
  Alice ->> bobby #005500: the right data
  return Another authentication Response
else bad password
  Alice ->> bobby #aa0000: one try
  return Another authentication Response
else bad email 
  Alice ->> bobby #aa0000: another try
  return Another authentication Response
end

note right #aqua: different ways of grouping: \n'group', 'loop', 'opt', 'alt/else', 'break', 'critical'.\n All groups must end with 'end'

=== grouping examples ==

  group My label [additional label]
    Alice ->> bobby #aa0000: another try
    return Another authentication Response
  end

  loop 100 times
    Alice ->> bobby #aa0000: another try
    return Another authentication Response
  end
==== h2 example (notes examples) ==
hnote over Alice: hexagonal note
rnote over bobby: rectangular note
note left of Alice: normal note left of alice
note right of bobby: normal note right of bobby
note across #00ffff: colored multi line note \n accross all parts \n other examples: https://plantuml.com/sequence-diagram
===== h3 example ==
====== h4 italic example ==
== normal text example ==

@enduml