@startuml
autoactivate on
actor user 
box Try Your Ideas
  participant TyiUI #cyan
  participant TyiAPI #cyan
  participant account #cyan
end box

user -> TyiUI: Sign Up Request 

TyiUI -> TyiAPI: sign Up

TyiAPI -> account: sign Up
account -> account: create user
return

return sign up result

return 
return Redirect to sign up page
@enduml