<template>
  <div class="bg-transparent text-transparent shadow-transparent border-transparent divide-transparent ring-transparent outline-transparent from-transparent via-transparent to-transparent fill-transparent accent-transparent ">-transparent </div>
  <div class="bg-white text-white shadow-white border-white divide-white ring-white outline-white from-white via-white to-white fill-white accent-white ">-white </div>
  <div class="bg-black text-black shadow-black border-black divide-black ring-black outline-black from-black via-black to-black fill-black accent-black ">-black </div>
  <div class="bg-inherit text-inherit shadow-inherit border-inherit divide-inherit ring-inherit outline-inherit from-inherit via-inherit to-inherit fill-inherit accent-inherit ">-inherit </div>
  <div class="bg-current text-current shadow-current border-current divide-current ring-current outline-current from-current via-current to-current fill-current accent-current ">-current </div>
  <div class="hover:bg-transparent hover:text-transparent hover:shadow-transparent hover:border-transparent hover:divide-transparent hover:ring-transparent hover:outline-transparent hover:from-transparent hover:via-transparent hover:to-transparent hover:fill-transparent hover:accent-transparent ">hover:-transparent </div>
  <div class="hover:bg-white hover:text-white hover:shadow-white hover:border-white hover:divide-white hover:ring-white hover:outline-white hover:from-white hover:via-white hover:to-white hover:fill-white hover:accent-white ">hover:-white </div>
  <div class="hover:bg-black hover:text-black hover:shadow-black hover:border-black hover:divide-black hover:ring-black hover:outline-black hover:from-black hover:via-black hover:to-black hover:fill-black hover:accent-black ">hover:-black </div>
  <div class="hover:bg-inherit hover:text-inherit hover:shadow-inherit hover:border-inherit hover:divide-inherit hover:ring-inherit hover:outline-inherit hover:from-inherit hover:via-inherit hover:to-inherit hover:fill-inherit hover:accent-inherit ">hover:-inherit </div>
  <div class="hover:bg-current hover:text-current hover:shadow-current hover:border-current hover:divide-current hover:ring-current hover:outline-current hover:from-current hover:via-current hover:to-current hover:fill-current hover:accent-current ">hover:-current </div>
  <div class="active:bg-transparent active:text-transparent active:shadow-transparent active:border-transparent active:divide-transparent active:ring-transparent active:outline-transparent active:from-transparent active:via-transparent active:to-transparent active:fill-transparent active:accent-transparent ">active:-transparent </div>
  <div class="active:bg-white active:text-white active:shadow-white active:border-white active:divide-white active:ring-white active:outline-white active:from-white active:via-white active:to-white active:fill-white active:accent-white ">active:-white </div>
  <div class="active:bg-black active:text-black active:shadow-black active:border-black active:divide-black active:ring-black active:outline-black active:from-black active:via-black active:to-black active:fill-black active:accent-black ">active:-black </div>
  <div class="active:bg-inherit active:text-inherit active:shadow-inherit active:border-inherit active:divide-inherit active:ring-inherit active:outline-inherit active:from-inherit active:via-inherit active:to-inherit active:fill-inherit active:accent-inherit ">active:-inherit </div>
  <div class="active:bg-current active:text-current active:shadow-current active:border-current active:divide-current active:ring-current active:outline-current active:from-current active:via-current active:to-current active:fill-current active:accent-current ">active:-current </div>
  <div class="focus:bg-transparent focus:text-transparent focus:shadow-transparent focus:border-transparent focus:divide-transparent focus:ring-transparent focus:outline-transparent focus:from-transparent focus:via-transparent focus:to-transparent focus:fill-transparent focus:accent-transparent ">focus:-transparent </div>
  <div class="focus:bg-white focus:text-white focus:shadow-white focus:border-white focus:divide-white focus:ring-white focus:outline-white focus:from-white focus:via-white focus:to-white focus:fill-white focus:accent-white ">focus:-white </div>
  <div class="focus:bg-black focus:text-black focus:shadow-black focus:border-black focus:divide-black focus:ring-black focus:outline-black focus:from-black focus:via-black focus:to-black focus:fill-black focus:accent-black ">focus:-black </div>
  <div class="focus:bg-inherit focus:text-inherit focus:shadow-inherit focus:border-inherit focus:divide-inherit focus:ring-inherit focus:outline-inherit focus:from-inherit focus:via-inherit focus:to-inherit focus:fill-inherit focus:accent-inherit ">focus:-inherit </div>
  <div class="focus:bg-current focus:text-current focus:shadow-current focus:border-current focus:divide-current focus:ring-current focus:outline-current focus:from-current focus:via-current focus:to-current focus:fill-current focus:accent-current ">focus:-current </div>
  
  </template>