<template>
  <div class="bg-transparent/20 text-transparent/20 shadow-transparent/20 border-transparent/20 divide-transparent/20 ring-transparent/20 outline-transparent/20 from-transparent/20 via-transparent/20 to-transparent/20 fill-transparent/20 accent-transparent/20  ">-transparent </div>
  <div class="bg-white/20 text-white/20 shadow-white/20 border-white/20 divide-white/20 ring-white/20 outline-white/20 from-white/20 via-white/20 to-white/20 fill-white/20 accent-white/20  ">-white </div>
  <div class="bg-black/20 text-black/20 shadow-black/20 border-black/20 divide-black/20 ring-black/20 outline-black/20 from-black/20 via-black/20 to-black/20 fill-black/20 accent-black/20  ">-black </div>
  <div class="bg-inherit/20 text-inherit/20 shadow-inherit/20 border-inherit/20 divide-inherit/20 ring-inherit/20 outline-inherit/20 from-inherit/20 via-inherit/20 to-inherit/20 fill-inherit/20 accent-inherit/20  ">-inherit </div>
  <div class="bg-current/20 text-current/20 shadow-current/20 border-current/20 divide-current/20 ring-current/20 outline-current/20 from-current/20 via-current/20 to-current/20 fill-current/20 accent-current/20  ">-current </div>
  <div class="hover:bg-transparent/20 hover:text-transparent/20 hover:shadow-transparent/20 hover:border-transparent/20 hover:divide-transparent/20 hover:ring-transparent/20 hover:outline-transparent/20 hover:from-transparent/20 hover:via-transparent/20 hover:to-transparent/20 hover:fill-transparent/20 hover:accent-transparent/20  ">hover:-transparent </div>
  <div class="hover:bg-white/20 hover:text-white/20 hover:shadow-white/20 hover:border-white/20 hover:divide-white/20 hover:ring-white/20 hover:outline-white/20 hover:from-white/20 hover:via-white/20 hover:to-white/20 hover:fill-white/20 hover:accent-white/20  ">hover:-white </div>
  <div class="hover:bg-black/20 hover:text-black/20 hover:shadow-black/20 hover:border-black/20 hover:divide-black/20 hover:ring-black/20 hover:outline-black/20 hover:from-black/20 hover:via-black/20 hover:to-black/20 hover:fill-black/20 hover:accent-black/20  ">hover:-black </div>
  <div class="hover:bg-inherit/20 hover:text-inherit/20 hover:shadow-inherit/20 hover:border-inherit/20 hover:divide-inherit/20 hover:ring-inherit/20 hover:outline-inherit/20 hover:from-inherit/20 hover:via-inherit/20 hover:to-inherit/20 hover:fill-inherit/20 hover:accent-inherit/20  ">hover:-inherit </div>
  <div class="hover:bg-current/20 hover:text-current/20 hover:shadow-current/20 hover:border-current/20 hover:divide-current/20 hover:ring-current/20 hover:outline-current/20 hover:from-current/20 hover:via-current/20 hover:to-current/20 hover:fill-current/20 hover:accent-current/20  ">hover:-current </div>
  <div class="active:bg-transparent/20 active:text-transparent/20 active:shadow-transparent/20 active:border-transparent/20 active:divide-transparent/20 active:ring-transparent/20 active:outline-transparent/20 active:from-transparent/20 active:via-transparent/20 active:to-transparent/20 active:fill-transparent/20 active:accent-transparent/20  ">active:-transparent </div>
  <div class="active:bg-white/20 active:text-white/20 active:shadow-white/20 active:border-white/20 active:divide-white/20 active:ring-white/20 active:outline-white/20 active:from-white/20 active:via-white/20 active:to-white/20 active:fill-white/20 active:accent-white/20  ">active:-white </div>
  <div class="active:bg-black/20 active:text-black/20 active:shadow-black/20 active:border-black/20 active:divide-black/20 active:ring-black/20 active:outline-black/20 active:from-black/20 active:via-black/20 active:to-black/20 active:fill-black/20 active:accent-black/20  ">active:-black </div>
  <div class="active:bg-inherit/20 active:text-inherit/20 active:shadow-inherit/20 active:border-inherit/20 active:divide-inherit/20 active:ring-inherit/20 active:outline-inherit/20 active:from-inherit/20 active:via-inherit/20 active:to-inherit/20 active:fill-inherit/20 active:accent-inherit/20  ">active:-inherit </div>
  <div class="active:bg-current/20 active:text-current/20 active:shadow-current/20 active:border-current/20 active:divide-current/20 active:ring-current/20 active:outline-current/20 active:from-current/20 active:via-current/20 active:to-current/20 active:fill-current/20 active:accent-current/20  ">active:-current </div>
  <div class="focus:bg-transparent/20 focus:text-transparent/20 focus:shadow-transparent/20 focus:border-transparent/20 focus:divide-transparent/20 focus:ring-transparent/20 focus:outline-transparent/20 focus:from-transparent/20 focus:via-transparent/20 focus:to-transparent/20 focus:fill-transparent/20 focus:accent-transparent/20  ">focus:-transparent </div>
  <div class="focus:bg-white/20 focus:text-white/20 focus:shadow-white/20 focus:border-white/20 focus:divide-white/20 focus:ring-white/20 focus:outline-white/20 focus:from-white/20 focus:via-white/20 focus:to-white/20 focus:fill-white/20 focus:accent-white/20  ">focus:-white </div>
  <div class="focus:bg-black/20 focus:text-black/20 focus:shadow-black/20 focus:border-black/20 focus:divide-black/20 focus:ring-black/20 focus:outline-black/20 focus:from-black/20 focus:via-black/20 focus:to-black/20 focus:fill-black/20 focus:accent-black/20  ">focus:-black </div>
  <div class="focus:bg-inherit/20 focus:text-inherit/20 focus:shadow-inherit/20 focus:border-inherit/20 focus:divide-inherit/20 focus:ring-inherit/20 focus:outline-inherit/20 focus:from-inherit/20 focus:via-inherit/20 focus:to-inherit/20 focus:fill-inherit/20 focus:accent-inherit/20  ">focus:-inherit </div>
  <div class="focus:bg-current/20 focus:text-current/20 focus:shadow-current/20 focus:border-current/20 focus:divide-current/20 focus:ring-current/20 focus:outline-current/20 focus:from-current/20 focus:via-current/20 focus:to-current/20 focus:fill-current/20 focus:accent-current/20  ">focus:-current </div>
  
  </template>