<template>
  <div class="bg-transparent/80 text-transparent/80 shadow-transparent/80 border-transparent/80 divide-transparent/80 ring-transparent/80 outline-transparent/80 from-transparent/80 via-transparent/80 to-transparent/80 fill-transparent/80 accent-transparent/80  ">-transparent </div>
  <div class="bg-white/80 text-white/80 shadow-white/80 border-white/80 divide-white/80 ring-white/80 outline-white/80 from-white/80 via-white/80 to-white/80 fill-white/80 accent-white/80  ">-white </div>
  <div class="bg-black/80 text-black/80 shadow-black/80 border-black/80 divide-black/80 ring-black/80 outline-black/80 from-black/80 via-black/80 to-black/80 fill-black/80 accent-black/80  ">-black </div>
  <div class="bg-inherit/80 text-inherit/80 shadow-inherit/80 border-inherit/80 divide-inherit/80 ring-inherit/80 outline-inherit/80 from-inherit/80 via-inherit/80 to-inherit/80 fill-inherit/80 accent-inherit/80  ">-inherit </div>
  <div class="bg-current/80 text-current/80 shadow-current/80 border-current/80 divide-current/80 ring-current/80 outline-current/80 from-current/80 via-current/80 to-current/80 fill-current/80 accent-current/80  ">-current </div>
  <div class="hover:bg-transparent/80 hover:text-transparent/80 hover:shadow-transparent/80 hover:border-transparent/80 hover:divide-transparent/80 hover:ring-transparent/80 hover:outline-transparent/80 hover:from-transparent/80 hover:via-transparent/80 hover:to-transparent/80 hover:fill-transparent/80 hover:accent-transparent/80  ">hover:-transparent </div>
  <div class="hover:bg-white/80 hover:text-white/80 hover:shadow-white/80 hover:border-white/80 hover:divide-white/80 hover:ring-white/80 hover:outline-white/80 hover:from-white/80 hover:via-white/80 hover:to-white/80 hover:fill-white/80 hover:accent-white/80  ">hover:-white </div>
  <div class="hover:bg-black/80 hover:text-black/80 hover:shadow-black/80 hover:border-black/80 hover:divide-black/80 hover:ring-black/80 hover:outline-black/80 hover:from-black/80 hover:via-black/80 hover:to-black/80 hover:fill-black/80 hover:accent-black/80  ">hover:-black </div>
  <div class="hover:bg-inherit/80 hover:text-inherit/80 hover:shadow-inherit/80 hover:border-inherit/80 hover:divide-inherit/80 hover:ring-inherit/80 hover:outline-inherit/80 hover:from-inherit/80 hover:via-inherit/80 hover:to-inherit/80 hover:fill-inherit/80 hover:accent-inherit/80  ">hover:-inherit </div>
  <div class="hover:bg-current/80 hover:text-current/80 hover:shadow-current/80 hover:border-current/80 hover:divide-current/80 hover:ring-current/80 hover:outline-current/80 hover:from-current/80 hover:via-current/80 hover:to-current/80 hover:fill-current/80 hover:accent-current/80  ">hover:-current </div>
  <div class="active:bg-transparent/80 active:text-transparent/80 active:shadow-transparent/80 active:border-transparent/80 active:divide-transparent/80 active:ring-transparent/80 active:outline-transparent/80 active:from-transparent/80 active:via-transparent/80 active:to-transparent/80 active:fill-transparent/80 active:accent-transparent/80  ">active:-transparent </div>
  <div class="active:bg-white/80 active:text-white/80 active:shadow-white/80 active:border-white/80 active:divide-white/80 active:ring-white/80 active:outline-white/80 active:from-white/80 active:via-white/80 active:to-white/80 active:fill-white/80 active:accent-white/80  ">active:-white </div>
  <div class="active:bg-black/80 active:text-black/80 active:shadow-black/80 active:border-black/80 active:divide-black/80 active:ring-black/80 active:outline-black/80 active:from-black/80 active:via-black/80 active:to-black/80 active:fill-black/80 active:accent-black/80  ">active:-black </div>
  <div class="active:bg-inherit/80 active:text-inherit/80 active:shadow-inherit/80 active:border-inherit/80 active:divide-inherit/80 active:ring-inherit/80 active:outline-inherit/80 active:from-inherit/80 active:via-inherit/80 active:to-inherit/80 active:fill-inherit/80 active:accent-inherit/80  ">active:-inherit </div>
  <div class="active:bg-current/80 active:text-current/80 active:shadow-current/80 active:border-current/80 active:divide-current/80 active:ring-current/80 active:outline-current/80 active:from-current/80 active:via-current/80 active:to-current/80 active:fill-current/80 active:accent-current/80  ">active:-current </div>
  <div class="focus:bg-transparent/80 focus:text-transparent/80 focus:shadow-transparent/80 focus:border-transparent/80 focus:divide-transparent/80 focus:ring-transparent/80 focus:outline-transparent/80 focus:from-transparent/80 focus:via-transparent/80 focus:to-transparent/80 focus:fill-transparent/80 focus:accent-transparent/80  ">focus:-transparent </div>
  <div class="focus:bg-white/80 focus:text-white/80 focus:shadow-white/80 focus:border-white/80 focus:divide-white/80 focus:ring-white/80 focus:outline-white/80 focus:from-white/80 focus:via-white/80 focus:to-white/80 focus:fill-white/80 focus:accent-white/80  ">focus:-white </div>
  <div class="focus:bg-black/80 focus:text-black/80 focus:shadow-black/80 focus:border-black/80 focus:divide-black/80 focus:ring-black/80 focus:outline-black/80 focus:from-black/80 focus:via-black/80 focus:to-black/80 focus:fill-black/80 focus:accent-black/80  ">focus:-black </div>
  <div class="focus:bg-inherit/80 focus:text-inherit/80 focus:shadow-inherit/80 focus:border-inherit/80 focus:divide-inherit/80 focus:ring-inherit/80 focus:outline-inherit/80 focus:from-inherit/80 focus:via-inherit/80 focus:to-inherit/80 focus:fill-inherit/80 focus:accent-inherit/80  ">focus:-inherit </div>
  <div class="focus:bg-current/80 focus:text-current/80 focus:shadow-current/80 focus:border-current/80 focus:divide-current/80 focus:ring-current/80 focus:outline-current/80 focus:from-current/80 focus:via-current/80 focus:to-current/80 focus:fill-current/80 focus:accent-current/80  ">focus:-current </div>
  
  </template>