<template>
  <div class="bg-transparent/10 text-transparent/10 shadow-transparent/10 border-transparent/10 divide-transparent/10 ring-transparent/10 outline-transparent/10 from-transparent/10 via-transparent/10 to-transparent/10 fill-transparent/10 accent-transparent/10  ">-transparent </div>
  <div class="bg-white/10 text-white/10 shadow-white/10 border-white/10 divide-white/10 ring-white/10 outline-white/10 from-white/10 via-white/10 to-white/10 fill-white/10 accent-white/10  ">-white </div>
  <div class="bg-black/10 text-black/10 shadow-black/10 border-black/10 divide-black/10 ring-black/10 outline-black/10 from-black/10 via-black/10 to-black/10 fill-black/10 accent-black/10  ">-black </div>
  <div class="bg-inherit/10 text-inherit/10 shadow-inherit/10 border-inherit/10 divide-inherit/10 ring-inherit/10 outline-inherit/10 from-inherit/10 via-inherit/10 to-inherit/10 fill-inherit/10 accent-inherit/10  ">-inherit </div>
  <div class="bg-current/10 text-current/10 shadow-current/10 border-current/10 divide-current/10 ring-current/10 outline-current/10 from-current/10 via-current/10 to-current/10 fill-current/10 accent-current/10  ">-current </div>
  <div class="hover:bg-transparent/10 hover:text-transparent/10 hover:shadow-transparent/10 hover:border-transparent/10 hover:divide-transparent/10 hover:ring-transparent/10 hover:outline-transparent/10 hover:from-transparent/10 hover:via-transparent/10 hover:to-transparent/10 hover:fill-transparent/10 hover:accent-transparent/10  ">hover:-transparent </div>
  <div class="hover:bg-white/10 hover:text-white/10 hover:shadow-white/10 hover:border-white/10 hover:divide-white/10 hover:ring-white/10 hover:outline-white/10 hover:from-white/10 hover:via-white/10 hover:to-white/10 hover:fill-white/10 hover:accent-white/10  ">hover:-white </div>
  <div class="hover:bg-black/10 hover:text-black/10 hover:shadow-black/10 hover:border-black/10 hover:divide-black/10 hover:ring-black/10 hover:outline-black/10 hover:from-black/10 hover:via-black/10 hover:to-black/10 hover:fill-black/10 hover:accent-black/10  ">hover:-black </div>
  <div class="hover:bg-inherit/10 hover:text-inherit/10 hover:shadow-inherit/10 hover:border-inherit/10 hover:divide-inherit/10 hover:ring-inherit/10 hover:outline-inherit/10 hover:from-inherit/10 hover:via-inherit/10 hover:to-inherit/10 hover:fill-inherit/10 hover:accent-inherit/10  ">hover:-inherit </div>
  <div class="hover:bg-current/10 hover:text-current/10 hover:shadow-current/10 hover:border-current/10 hover:divide-current/10 hover:ring-current/10 hover:outline-current/10 hover:from-current/10 hover:via-current/10 hover:to-current/10 hover:fill-current/10 hover:accent-current/10  ">hover:-current </div>
  <div class="active:bg-transparent/10 active:text-transparent/10 active:shadow-transparent/10 active:border-transparent/10 active:divide-transparent/10 active:ring-transparent/10 active:outline-transparent/10 active:from-transparent/10 active:via-transparent/10 active:to-transparent/10 active:fill-transparent/10 active:accent-transparent/10  ">active:-transparent </div>
  <div class="active:bg-white/10 active:text-white/10 active:shadow-white/10 active:border-white/10 active:divide-white/10 active:ring-white/10 active:outline-white/10 active:from-white/10 active:via-white/10 active:to-white/10 active:fill-white/10 active:accent-white/10  ">active:-white </div>
  <div class="active:bg-black/10 active:text-black/10 active:shadow-black/10 active:border-black/10 active:divide-black/10 active:ring-black/10 active:outline-black/10 active:from-black/10 active:via-black/10 active:to-black/10 active:fill-black/10 active:accent-black/10  ">active:-black </div>
  <div class="active:bg-inherit/10 active:text-inherit/10 active:shadow-inherit/10 active:border-inherit/10 active:divide-inherit/10 active:ring-inherit/10 active:outline-inherit/10 active:from-inherit/10 active:via-inherit/10 active:to-inherit/10 active:fill-inherit/10 active:accent-inherit/10  ">active:-inherit </div>
  <div class="active:bg-current/10 active:text-current/10 active:shadow-current/10 active:border-current/10 active:divide-current/10 active:ring-current/10 active:outline-current/10 active:from-current/10 active:via-current/10 active:to-current/10 active:fill-current/10 active:accent-current/10  ">active:-current </div>
  <div class="focus:bg-transparent/10 focus:text-transparent/10 focus:shadow-transparent/10 focus:border-transparent/10 focus:divide-transparent/10 focus:ring-transparent/10 focus:outline-transparent/10 focus:from-transparent/10 focus:via-transparent/10 focus:to-transparent/10 focus:fill-transparent/10 focus:accent-transparent/10  ">focus:-transparent </div>
  <div class="focus:bg-white/10 focus:text-white/10 focus:shadow-white/10 focus:border-white/10 focus:divide-white/10 focus:ring-white/10 focus:outline-white/10 focus:from-white/10 focus:via-white/10 focus:to-white/10 focus:fill-white/10 focus:accent-white/10  ">focus:-white </div>
  <div class="focus:bg-black/10 focus:text-black/10 focus:shadow-black/10 focus:border-black/10 focus:divide-black/10 focus:ring-black/10 focus:outline-black/10 focus:from-black/10 focus:via-black/10 focus:to-black/10 focus:fill-black/10 focus:accent-black/10  ">focus:-black </div>
  <div class="focus:bg-inherit/10 focus:text-inherit/10 focus:shadow-inherit/10 focus:border-inherit/10 focus:divide-inherit/10 focus:ring-inherit/10 focus:outline-inherit/10 focus:from-inherit/10 focus:via-inherit/10 focus:to-inherit/10 focus:fill-inherit/10 focus:accent-inherit/10  ">focus:-inherit </div>
  <div class="focus:bg-current/10 focus:text-current/10 focus:shadow-current/10 focus:border-current/10 focus:divide-current/10 focus:ring-current/10 focus:outline-current/10 focus:from-current/10 focus:via-current/10 focus:to-current/10 focus:fill-current/10 focus:accent-current/10  ">focus:-current </div>
  
  </template>