<template>
  <div class="bg-transparent/90 text-transparent/90 shadow-transparent/90 border-transparent/90 divide-transparent/90 ring-transparent/90 outline-transparent/90 from-transparent/90 via-transparent/90 to-transparent/90 fill-transparent/90 accent-transparent/90  ">-transparent </div>
  <div class="bg-white/90 text-white/90 shadow-white/90 border-white/90 divide-white/90 ring-white/90 outline-white/90 from-white/90 via-white/90 to-white/90 fill-white/90 accent-white/90  ">-white </div>
  <div class="bg-black/90 text-black/90 shadow-black/90 border-black/90 divide-black/90 ring-black/90 outline-black/90 from-black/90 via-black/90 to-black/90 fill-black/90 accent-black/90  ">-black </div>
  <div class="bg-inherit/90 text-inherit/90 shadow-inherit/90 border-inherit/90 divide-inherit/90 ring-inherit/90 outline-inherit/90 from-inherit/90 via-inherit/90 to-inherit/90 fill-inherit/90 accent-inherit/90  ">-inherit </div>
  <div class="bg-current/90 text-current/90 shadow-current/90 border-current/90 divide-current/90 ring-current/90 outline-current/90 from-current/90 via-current/90 to-current/90 fill-current/90 accent-current/90  ">-current </div>
  <div class="hover:bg-transparent/90 hover:text-transparent/90 hover:shadow-transparent/90 hover:border-transparent/90 hover:divide-transparent/90 hover:ring-transparent/90 hover:outline-transparent/90 hover:from-transparent/90 hover:via-transparent/90 hover:to-transparent/90 hover:fill-transparent/90 hover:accent-transparent/90  ">hover:-transparent </div>
  <div class="hover:bg-white/90 hover:text-white/90 hover:shadow-white/90 hover:border-white/90 hover:divide-white/90 hover:ring-white/90 hover:outline-white/90 hover:from-white/90 hover:via-white/90 hover:to-white/90 hover:fill-white/90 hover:accent-white/90  ">hover:-white </div>
  <div class="hover:bg-black/90 hover:text-black/90 hover:shadow-black/90 hover:border-black/90 hover:divide-black/90 hover:ring-black/90 hover:outline-black/90 hover:from-black/90 hover:via-black/90 hover:to-black/90 hover:fill-black/90 hover:accent-black/90  ">hover:-black </div>
  <div class="hover:bg-inherit/90 hover:text-inherit/90 hover:shadow-inherit/90 hover:border-inherit/90 hover:divide-inherit/90 hover:ring-inherit/90 hover:outline-inherit/90 hover:from-inherit/90 hover:via-inherit/90 hover:to-inherit/90 hover:fill-inherit/90 hover:accent-inherit/90  ">hover:-inherit </div>
  <div class="hover:bg-current/90 hover:text-current/90 hover:shadow-current/90 hover:border-current/90 hover:divide-current/90 hover:ring-current/90 hover:outline-current/90 hover:from-current/90 hover:via-current/90 hover:to-current/90 hover:fill-current/90 hover:accent-current/90  ">hover:-current </div>
  <div class="active:bg-transparent/90 active:text-transparent/90 active:shadow-transparent/90 active:border-transparent/90 active:divide-transparent/90 active:ring-transparent/90 active:outline-transparent/90 active:from-transparent/90 active:via-transparent/90 active:to-transparent/90 active:fill-transparent/90 active:accent-transparent/90  ">active:-transparent </div>
  <div class="active:bg-white/90 active:text-white/90 active:shadow-white/90 active:border-white/90 active:divide-white/90 active:ring-white/90 active:outline-white/90 active:from-white/90 active:via-white/90 active:to-white/90 active:fill-white/90 active:accent-white/90  ">active:-white </div>
  <div class="active:bg-black/90 active:text-black/90 active:shadow-black/90 active:border-black/90 active:divide-black/90 active:ring-black/90 active:outline-black/90 active:from-black/90 active:via-black/90 active:to-black/90 active:fill-black/90 active:accent-black/90  ">active:-black </div>
  <div class="active:bg-inherit/90 active:text-inherit/90 active:shadow-inherit/90 active:border-inherit/90 active:divide-inherit/90 active:ring-inherit/90 active:outline-inherit/90 active:from-inherit/90 active:via-inherit/90 active:to-inherit/90 active:fill-inherit/90 active:accent-inherit/90  ">active:-inherit </div>
  <div class="active:bg-current/90 active:text-current/90 active:shadow-current/90 active:border-current/90 active:divide-current/90 active:ring-current/90 active:outline-current/90 active:from-current/90 active:via-current/90 active:to-current/90 active:fill-current/90 active:accent-current/90  ">active:-current </div>
  <div class="focus:bg-transparent/90 focus:text-transparent/90 focus:shadow-transparent/90 focus:border-transparent/90 focus:divide-transparent/90 focus:ring-transparent/90 focus:outline-transparent/90 focus:from-transparent/90 focus:via-transparent/90 focus:to-transparent/90 focus:fill-transparent/90 focus:accent-transparent/90  ">focus:-transparent </div>
  <div class="focus:bg-white/90 focus:text-white/90 focus:shadow-white/90 focus:border-white/90 focus:divide-white/90 focus:ring-white/90 focus:outline-white/90 focus:from-white/90 focus:via-white/90 focus:to-white/90 focus:fill-white/90 focus:accent-white/90  ">focus:-white </div>
  <div class="focus:bg-black/90 focus:text-black/90 focus:shadow-black/90 focus:border-black/90 focus:divide-black/90 focus:ring-black/90 focus:outline-black/90 focus:from-black/90 focus:via-black/90 focus:to-black/90 focus:fill-black/90 focus:accent-black/90  ">focus:-black </div>
  <div class="focus:bg-inherit/90 focus:text-inherit/90 focus:shadow-inherit/90 focus:border-inherit/90 focus:divide-inherit/90 focus:ring-inherit/90 focus:outline-inherit/90 focus:from-inherit/90 focus:via-inherit/90 focus:to-inherit/90 focus:fill-inherit/90 focus:accent-inherit/90  ">focus:-inherit </div>
  <div class="focus:bg-current/90 focus:text-current/90 focus:shadow-current/90 focus:border-current/90 focus:divide-current/90 focus:ring-current/90 focus:outline-current/90 focus:from-current/90 focus:via-current/90 focus:to-current/90 focus:fill-current/90 focus:accent-current/90  ">focus:-current </div>
  
  </template>