<template>
  <div class="transition-none ">-none </div>
  <div class="transition-all ">-all </div>
  <div class="transition-colors ">-colors </div>
  <div class="transition-opacity ">-opacity </div>
  <div class="transition-shadow ">-shadow </div>
  <div class="transition-transform ">-transform </div>
  <div class="hover:transition-none ">hover:-none </div>
  <div class="hover:transition-all ">hover:-all </div>
  <div class="hover:transition-colors ">hover:-colors </div>
  <div class="hover:transition-opacity ">hover:-opacity </div>
  <div class="hover:transition-shadow ">hover:-shadow </div>
  <div class="hover:transition-transform ">hover:-transform </div>
  <div class="active:transition-none ">active:-none </div>
  <div class="active:transition-all ">active:-all </div>
  <div class="active:transition-colors ">active:-colors </div>
  <div class="active:transition-opacity ">active:-opacity </div>
  <div class="active:transition-shadow ">active:-shadow </div>
  <div class="active:transition-transform ">active:-transform </div>
  <div class="focus:transition-none ">focus:-none </div>
  <div class="focus:transition-all ">focus:-all </div>
  <div class="focus:transition-colors ">focus:-colors </div>
  <div class="focus:transition-opacity ">focus:-opacity </div>
  <div class="focus:transition-shadow ">focus:-shadow </div>
  <div class="focus:transition-transform ">focus:-transform </div>
  
  <div class="delay-0 duration-0 ">-0 </div>
  <div class="delay-75 duration-75 ">-75 </div>
  <div class="delay-100 duration-100 ">-100 </div>
  <div class="delay-150 duration-150 ">-150 </div>
  <div class="delay-200 duration-200 ">-200 </div>
  <div class="delay-300 duration-300 ">-300 </div>
  <div class="delay-500 duration-500 ">-500 </div>
  <div class="delay-700 duration-700 ">-700 </div>
  <div class="delay-1000 duration-1000 ">-1000 </div>
  <div class="hover:delay-0 hover:duration-0 ">hover:-0 </div>
  <div class="hover:delay-75 hover:duration-75 ">hover:-75 </div>
  <div class="hover:delay-100 hover:duration-100 ">hover:-100 </div>
  <div class="hover:delay-150 hover:duration-150 ">hover:-150 </div>
  <div class="hover:delay-200 hover:duration-200 ">hover:-200 </div>
  <div class="hover:delay-300 hover:duration-300 ">hover:-300 </div>
  <div class="hover:delay-500 hover:duration-500 ">hover:-500 </div>
  <div class="hover:delay-700 hover:duration-700 ">hover:-700 </div>
  <div class="hover:delay-1000 hover:duration-1000 ">hover:-1000 </div>
  <div class="active:delay-0 active:duration-0 ">active:-0 </div>
  <div class="active:delay-75 active:duration-75 ">active:-75 </div>
  <div class="active:delay-100 active:duration-100 ">active:-100 </div>
  <div class="active:delay-150 active:duration-150 ">active:-150 </div>
  <div class="active:delay-200 active:duration-200 ">active:-200 </div>
  <div class="active:delay-300 active:duration-300 ">active:-300 </div>
  <div class="active:delay-500 active:duration-500 ">active:-500 </div>
  <div class="active:delay-700 active:duration-700 ">active:-700 </div>
  <div class="active:delay-1000 active:duration-1000 ">active:-1000 </div>
  <div class="focus:delay-0 focus:duration-0 ">focus:-0 </div>
  <div class="focus:delay-75 focus:duration-75 ">focus:-75 </div>
  <div class="focus:delay-100 focus:duration-100 ">focus:-100 </div>
  <div class="focus:delay-150 focus:duration-150 ">focus:-150 </div>
  <div class="focus:delay-200 focus:duration-200 ">focus:-200 </div>
  <div class="focus:delay-300 focus:duration-300 ">focus:-300 </div>
  <div class="focus:delay-500 focus:duration-500 ">focus:-500 </div>
  <div class="focus:delay-700 focus:duration-700 ">focus:-700 </div>
  <div class="focus:delay-1000 focus:duration-1000 ">focus:-1000 </div>
 
  <div class="ease-linear ">-linear </div>
  <div class="ease-in ">-in </div>
  <div class="ease-out ">-out </div>
  <div class="ease-in-out ">-in-out </div>
  <div class="hover:ease-linear ">hover:-linear </div>
  <div class="hover:ease-in ">hover:-in </div>
  <div class="hover:ease-out ">hover:-out </div>
  <div class="hover:ease-in-out ">hover:-in-out </div>
  <div class="active:ease-linear ">active:-linear </div>
  <div class="active:ease-in ">active:-in </div>
  <div class="active:ease-out ">active:-out </div>
  <div class="active:ease-in-out ">active:-in-out </div>
  <div class="focus:ease-linear ">focus:-linear </div>
  <div class="focus:ease-in ">focus:-in </div>
  <div class="focus:ease-out ">focus:-out </div>
  <div class="focus:ease-in-out ">focus:-in-out </div>
  
  <div class="animate-none ">-none </div>
  <div class="animate-spin ">-spin </div>
  <div class="animate-ping ">-ping </div>
  <div class="animate-pulse ">-pulse </div>
  <div class="animate-bounce ">-bounce </div>
  <div class="hover:animate-none ">hover:-none </div>
  <div class="hover:animate-spin ">hover:-spin </div>
  <div class="hover:animate-ping ">hover:-ping </div>
  <div class="hover:animate-pulse ">hover:-pulse </div>
  <div class="hover:animate-bounce ">hover:-bounce </div>
  <div class="active:animate-none ">active:-none </div>
  <div class="active:animate-spin ">active:-spin </div>
  <div class="active:animate-ping ">active:-ping </div>
  <div class="active:animate-pulse ">active:-pulse </div>
  <div class="active:animate-bounce ">active:-bounce </div>
  <div class="focus:animate-none ">focus:-none </div>
  <div class="focus:animate-spin ">focus:-spin </div>
  <div class="focus:animate-ping ">focus:-ping </div>
  <div class="focus:animate-pulse ">focus:-pulse </div>
  <div class="focus:animate-bounce ">focus:-bounce </div> 

</template>
